[package]
name = "cc-search"
version.workspace = true
edition.workspace = true

[features]
default = ["regexp-udf"]
regexp-udf = ["rusqlite/functions"]

[dependencies]
cc-model = { path = "../cc-model" }
cc-db = { path = "../cc-db" }
regex.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
rusqlite.workspace = true
lru.workspace = true
rayon.workspace = true

[dev-dependencies]
tempfile = "3"
