#!/usr/bin/env python3
"""Read the completed finalization ZIP and export exact generated bytes in four bounded parts."""
import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import stat
import subprocess
import sys
import urllib.request
import zipfile
from inspect_fixed_artifacts import NoRedirect, authenticated, copy_archive

BASE = "artifacts/checkpoints/p7-final-acceptance-20261008"
EXPECTED = {"id":11530438503, "name":"p7-reviewed-finalization-188c7a21a12e3ad1ad42fd91d05f67d784de9982",
            "bytes":2628476, "sha256":"6ad8e2e51cafac1bcf44cffdeefd81e075714375a175690a3b88c3be78593ccb",
            "run_id":37734085899, "head_sha":"188c7a21a12e3ad1ad42fd91d05f67d784de9982"}
def sha(raw):
    return hashlib.sha256(raw).hexdigest()

parser = argparse.ArgumentParser()
parser.add_argument("--part", type=int, required=True)
parser.add_argument("--output", type=Path, required=True)
args = parser.parse_args()
assert sys.flags.optimize == 0 and 0 <= args.part < 4
args.output.mkdir(parents=True, exist_ok=False)
api = "https://api.github.com/repos/jyqj/codecortex/actions/artifacts/" + str(EXPECTED["id"])
token = os.environ["GH_TOKEN"]
with urllib.request.build_opener(NoRedirect()).open(authenticated(api, token), timeout=60) as response:
    assert response.status == 200
    metadata = json.load(response)
assert metadata["id"] == EXPECTED["id"] and metadata["name"] == EXPECTED["name"]
assert metadata["size_in_bytes"] == EXPECTED["bytes"] and not metadata["expired"]
assert metadata["digest"] == "sha256:" + EXPECTED["sha256"]
assert metadata["workflow_run"]["id"] == EXPECTED["run_id"]
assert metadata["workflow_run"]["head_sha"] == EXPECTED["head_sha"]
archive_path = args.output.parent / ("finalization-" + str(args.part) + ".zip")
copy_archive(api + "/zip", token, archive_path, EXPECTED)
rows = []
with zipfile.ZipFile(archive_path) as z:
    names = z.namelist()
    assert len(names) == len(set(names))
    suffix = BASE + "/task-transition-receipt.json"
    candidates = [n for n in names if n.endswith(suffix)]
    assert len(candidates) == 1, "unique actual finalization receipt missing"
    prefix = candidates[0][:-len(suffix)]
    for info in z.infolist():
        path = PurePosixPath(info.filename)
        assert not path.is_absolute() and ".." not in path.parts and "\\" not in info.filename
        assert not stat.S_ISLNK(info.external_attr >> 16)
        if info.is_dir() or not info.filename.startswith(prefix):
            continue
        relative = info.filename[len(prefix):]
        assert relative == "README.md" or relative.startswith(("artifacts/", "docs/"))
        raw = z.read(info)
        assert len(raw) == info.file_size
        text = raw.decode("utf-8")
        assert text.encode("utf-8") == raw
        rows.append({"path":relative, "bytes":len(raw), "sha256":sha(raw), "raw":raw,
                     "estimated_export_bytes":len(json.dumps(text, ensure_ascii=True)) + 500 + (len(text)//8000+1)*(len(relative)+180)})
assert len(rows) == 288, "unexpected completed finalization file inventory"
by_path = {r["path"]:r for r in rows}
assert len(by_path) == len(rows)
task = by_path["docs/roadmap/code-index-v2/tasks.json"]
assert task["sha256"] == "b5a33e7827a6a1b60b71194348d61eb629385c48c1b970f434f330b2244a0812"
transition = json.loads(by_path[suffix]["raw"])
assert transition["status"] == "passed" and transition["unfinished_after"] == 32
assert transition["source_snapshot_unchanged"] and transition["utility_workflow_absent_from_candidate"]
loads = [0,0,0,0]
for row in sorted(rows, key=lambda r:(-r["estimated_export_bytes"],r["path"])):
    part = min(range(4), key=lambda i:(loads[i],i))
    row["part"] = part
    loads[part] += row["estimated_export_bytes"]
inventory = [{k:v for k,v in r.items() if k != "raw"} for r in sorted(rows,key=lambda r:r["path"])]
inventory_raw = (json.dumps(inventory, ensure_ascii=True, sort_keys=True) + "\n").encode()
selected = [r for r in rows if r["part"] == args.part]
for row in selected:
    target = args.output / row["path"]
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_bytes(row["raw"])
    target.chmod(0o644)
print("P7_FINAL_PART_IDENTITY " + json.dumps({
    "schema_version":1,"part":args.part,"parts":4,"artifact":EXPECTED,
    "derived_archive_prefix":prefix,"complete_file_count":len(rows),
    "complete_raw_bytes":sum(r["bytes"] for r in rows),
    "allocation_manifest_sha256":sha(inventory_raw),"estimated_part_bytes":loads,
    "selected_file_count":len(selected),"selected_bytes":sum(r["bytes"] for r in selected),
    "scope":"Exact bytes from already successful finalization; no source mutation, task recalculation or product rerun."
},ensure_ascii=True),flush=True)
subprocess.run([sys.executable,str(Path(__file__).with_name("export_audit_outputs.py")),
                "--root",str(args.output),"--prefix","."],check=True)
