import pathlib,json,hashlib,subprocess,importlib.util,sys
sys.dont_write_bytecode=True
root=pathlib.Path(__file__).resolve().parent;repo=root.parents[2];manifest=json.loads((root/'artifact-manifest.json').read_text())
for x in manifest:assert hashlib.sha256((root/x['path']).read_bytes()).hexdigest()==x['sha256'],x['path']
s=importlib.util.spec_from_file_location('replay',root/'analyze.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);a=m.analyze();assert a==json.loads((root/'measurements-at-checkpoint.json').read_text());assert len(a['cells'])==8 and sum(c['N'] for c in a['cells'])==256 and all(c['errors']==0 and c['empty_hits']==0 for c in a['cells'])
x=json.loads((root/'summary.json').read_text());assert x['status']=='completed_prepared' and x['scales'][0]['product_exit_code']==0 and all(c['peak_client_inflight']==c['concurrency_cap'] and not c['errors'] for c in x['cells']);f=json.loads((root/'fixed/n50000/final-db.json').read_text());assert f['integrity']=='ok' and f['foreign_key_errors']==0 and f['counts']['files']==f['counts']['semantic_manifest']==50000;assert json.loads((root/'fixed/n50000/final-status.json').read_text())['semantic_state']=='ready'
h=json.loads((root/'handoff.json').read_text());b=json.loads((root/'build-receipt.json').read_text());assert b['source_sha']==h['production_source_sha'] and b['build_exit_code']==0 and b['guard_stop'] is None and b['profile']=='release' and b['binary_sha256']==x['binary_sha256']==h['binary_sha256'];assert b['compiler_artifact']['profile']['opt_level']=='3' and not b['compiler_artifact']['profile']['debug_assertions'];assert sorted(b['compiler_artifact']['features'])==['semantic','semantic-http']
assert not h['natural_end_needed'] and all(p['state']=='absent' for p in h['processes'].values());assert subprocess.check_output(['git','show',h['production_source_sha']+':crates/cc-db/src/index_db_edges.rs'],cwd=repo)==(repo/'crates/cc-db/src/index_db_edges.rs').read_bytes()
print(json.dumps({'status':'passed','hashes':len(manifest),'completed_release_scale':50000,'requests':256,'full_V20':False}))
