from pathlib import Path
import json,hashlib,collections,datetime
root=Path.cwd();review=root/'review-runtime';source=root/'source'
def read(p):return json.loads(p.read_text())
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
specs=[(1,11592751905,113631481248,'6cfceee02ed7fcd71039b9870e48457ddb3a7607935c7a5e798d549ee33123da'),(4,11591493782,113631481184,'727ab17068655b9ee5cd5677fb3f1a9fb4460c87266dfb0e6628d9a75678502c'),(8,11593165899,113631481186,'427906a25d21afae8085328c8fc92d6997763b1ad0f52247118052ec788118b8'),(16,11592154271,113631481232,'9ca7ff34acba74969feb840837d48ad89952efe06a9d02733c7c29d92efdf487')]
matrix=[]
for c,aid,jid,digest in specs:
 file=review/('runtime-'+str(aid)+'-review-v2.json');r=read(file);original=read(root/'raw'/str(aid)/'extracted/p8-runtime/report.json')
 assert r['review_status']=='raw_and_receipt_review_passed' and r['errors']==[]
 assert sha(root/'raw'/str(aid)/'original.zip')==digest
 matrix.append({'configured_concurrency':c,'actual_call_peak':r['actual_concurrency']['maximum'],'independent_call_peak':r['independent_call_interval_maximum'],'read_build_overlap':r['actual_concurrency']['read_build_overlap'],'offered':900,'successful':900,'read_samples':r['outcomes']['read'],'build_samples':r['outcomes']['build'],'original_real_branch_switches':r['branch_switches'],'original_catalog_compactions':r['catalog_compactions'],'original_native_rss_samples':r['raw_kind_counts']['resources'],'native_oracle_equal_tables':len(r['parity_tables']),'no_extra_index_calls':r['stdio_counts']['product']['index']==301,'original_statistics_double_replay_identical':original['statistics']['replay_identical'],'artifact_id':aid,'artifact_zip_sha256':digest,'job_url':'https://github.com/jyqj/codecortex/actions/runs/37871838957/job/'+str(jid),'artifact_url':'https://github.com/jyqj/codecortex/actions/runs/37871838957/artifacts/'+str(aid),'review_file':file.name,'review_sha256':sha(file),'measurement_file':'../raw/'+str(aid)+'/extracted/p8-runtime/report.json','raw_file':'../raw/'+str(aid)+'/extracted/p8-runtime/raw.jsonl','statistics_file':'../raw/'+str(aid)+'/extracted/p8-runtime/statistics.json','parity_file':'../raw/'+str(aid)+'/extracted/p8-runtime/parity.json','unbounded_p99_groups':[{'operation':g['operation'],'mutation_action':g['mutation_action'],'samples':g['n']} for g in r['statistics_groups'] if g['latency']['p99_ci']['upper_us'] is None]})
backfill=read(review/'backfill-11591821446-review.json');life=read(review/'lifecycle-11591607348-review-v2.json')
assert backfill['review_status']==life['review_status']=='raw_and_receipt_review_passed' and not backfill['errors'] and not life['errors']
tasks_obj=read(source/'docs/roadmap/code-index-v2/tasks.json');tasks=tasks_obj['tasks'] if isinstance(tasks_obj,dict) else tasks_obj
counts=collections.Counter(x['status'] for x in tasks);task_by_id={x['id']:x for x in tasks}
assert counts['done']==163 and len(tasks)-counts['done']==29
identity={'source_sha':'a23bb72d3c954f385b99fe81ce9189885c208557','source_tree':'58147c952505c44da1f41eb4b9c31643f2303b96','crate_cargo_input_count':1087,'crate_cargo_manifest_sha256':'4e0aa6bbfd4d5bea00416bca2cd99318d865ffc526fdcb45897c4d300de3ac00'}
mapping={
'P8-007':{'task_title':task_by_id['P8-007']['title'],'original_dependencies':task_by_id['P8-007']['depends_on'],'assessment':'four original mixed profiles and original fake-provider worker observations completed and independently reviewed; task remains open pending original dependencies and wider regression/acceptance review','evidence':{'mixed':matrix,'fake_backfill':{'artifact_id':11591821446,'zip_sha256':'24fa1251fa006d23df2f801a7d5ba7eb420223c4a7dbd0cce7ab8fdcf6b36e15','job_url':'https://github.com/jyqj/codecortex/actions/runs/37871838957/job/113631480994','review_file':'backfill-11591821446-review.json','review_sha256':sha(review/'backfill-11591821446-review.json'),'requests':768,'seeds':[7,19,43],'phases':['quiet','held'],'concurrency_cells':[1,4,8,16],'samples_per_cell':32,'original_query_watchdog_ms':2000,'original_progress_watchdog_ms':5000,'original_writer_timeout_ms':100,'maximum_provider_active_per_seed':4,'old_space_publications_per_seed':0,'pending_claimed_uncovered_final_per_seed':0,'external_provider_scope':'fake provider in same process; no live-provider acceptance or new tail SLA'}}},
'P8-008':{'task_title':task_by_id['P8-008']['title'],'original_dependencies':task_by_id['P8-008']['depends_on'],'assessment':'original release lifecycle observations completed and independently reviewed; task remains open for dependency and regression closeout','artifact_id':11591607348,'zip_sha256':'63aadf94879ea86782e9759828e853c1a030d70014fdc3fbdc127a18ca2eb055','run_url':'https://github.com/jyqj/codecortex/actions/runs/37871838975','review_file':'lifecycle-11591607348-review-v2.json','review_sha256':sha(review/'lifecycle-11591607348-review-v2.json'),'original_samples':{'cold_build':30,'process_reopen':400,'warm_uncached':400,'cache_hit':400,'total':1230,'separate_unmeasured_warmup':1},'original_sessions':431,'raw_query_witnesses':1200,'source_verified_queries':1200,'all_recorded_samples_successful':True,'actual_native_evaluator_double_replay_identical':True,'latency_layers':life['latency_layers'],'os_page_cache':'unknown_not_cold_disk','primary_replay_paths':['../raw/11591607348/extracted/measurement/replay-input.json','../raw/11591607348/extracted/measurement/report.json','../raw/11591607348/extracted/measurement/report-replayed.json','../raw/11591607348/extracted/measurement/repeat-replay-receipt.json']},
'P8-009':{'task_title':task_by_id['P8-009']['title'],'original_dependencies':task_by_id['P8-009']['depends_on'],'assessment':'actual resource/storage/cost attribution independently reviewed; permitted unknowns remain unavailable and are not added as new certification gates; task still awaits dependency and wider acceptance closeout','artifact_id':11591607348,'review_file':'lifecycle-11591607348-review-v2.json','resource_snapshots':1261,'native_tree_member_counts':life['tree_member_counts'],'memory_ledger':life['memory_ledger'],'disk_ledger':life['disk_ledger'],'physical_components':life['physical_components'],'observed_zero_byte_objects':life['observed_zero_byte_objects'],'logical_fts_by_fixture':life['logical_fts_by_fixture'],'artifact_logical_size_observation':life['artifact_bytes_original_observation'],'provider_cost':life['provider_cost'],'attribution_rules':['client native SELF separate from server native SELF','server process already included in its owned process tree; never sum them','native client/server/tree stage maxima may be at different instants; total RSS remains null','ps/native alternatives and different process peaks are not added','runtime native RSS and lifecycle tree snapshots are distinct profiles and are not merged into continuous tree coverage','90 original physical storage identities from 30 closed cold fixtures count once; this is not one active index footprint','logical FTS pages are within shared physical SQLite bytes','reported and estimated billing fields remain separate and null for disabled provider; no zero-charge inference','server CPU deltas use native nanoseconds and include bracketing status observation work; runner SELF seconds remain labeled seconds','process IO storage bytes, logical characters and syscall counts keep distinct units'],'raw_evidence':['../raw/11591607348/extracted/measurement/events.jsonl','../raw/11591607348/extracted/measurement/replay-input.json','../raw/11591607348/extracted/measurement/receipt.json']},
'P8-010':{'task_title':task_by_id['P8-010']['title'],'original_dependencies':task_by_id['P8-010']['depends_on'],'assessment':'original one-hour a23 soak is still running; no completion claim','run_id':37871838957,'job_id':113631481157,'workload_step_started_at':'2026-10-09T02:48:58Z','original_plan':{'files':1000,'configured_concurrency':4,'operations':3601,'builds':1201,'compound_reads':2400,'roles_per_read':['before_status','symbol','hybrid','after_status'],'required_actual_work_ns':3600000000000},'pending_original_gates':['complete original terminal denominator and native statistics double replay','original native RSS trend and <=5 second coverage gaps','actual catalog compactions and >=2 real branch switches','original compound-cache validator with actual completed-mutation quarter boundaries and hit/miss/invalidation in all quarters','original no-repair independent full 15-table endpoint parity','all owned processes and work drained before final sealing']},
'P8-011':{'task_title':task_by_id['P8-011']['title'],'original_dependencies':task_by_id['P8-011']['depends_on'],'assessment':'separate original failure-gates evidence and dependencies remain outside this runtime/lifecycle review; no closure inferred here'}
}
out={'schema_version':1,'review_round':4,'updated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':{'total_tasks':len(tasks),'done':163,'remaining':29,'new_task_closures_from_this_review':0,'status_counts':dict(counts)},'identity':identity,'review_status':'six completed original component observations independently reviewed; original soak pending','tasks':mapping,'reviewer':'independent pr_triage subagent; no original source/workflow/workload/validator mutation','review_programs':{p.name:sha(p) for p in [review/'runtime-independent-review-v2.py',review/'lifecycle-independent-review-v2.py',review/'backfill-independent-review.py']},'scope_limits':['original Linux native collectors and product/oracle executed in GitHub; macOS work here is artifact review, not a new Linux or macOS product experiment','original native replay receipts retained; Linux ELF/current-original-Cargo-target execution contract was not rerun on macOS','sample populations remain stratified by protocol/profile/configured concurrency; overlapping statistics views never pool to meet a sample floor','all original task dependencies and acceptance remain; passing sealed files alone cannot close a task']}
path=review/'round4-p8-007-009-evidence-map.json';path.write_text(json.dumps(out,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
lines=['# 第 4 轮：P8 运行时与账本独立审查','','原任务基线仍为 **163 done /29 剩余**。本次审查没有提前关闭 TODO，也没有修改原 workflow、source、工作量或验收器。','','固定 source：`a23bb72d3c954f385b99fe81ce9189885c208557`；1087 个 crate/Cargo 输入及相应 observer 原件均已逐文件绑定。四档 mixed 与 fake backfill 的原观测、以及 lifecycle 原观测已完成独立审查；原 1 小时 soak 仍在运行。','','## P8-007：原四档 mixed 与 backfill','','[原 runtime run](https://github.com/jyqj/codecortex/actions/runs/37871838957) 的每档固定为 1000 files、900 offered operations（300 build、600 read），按原并发大小的固定 burst 日程投递。','','| 配置 | 实际调用峰值 | 原操作成功 | read/build 重叠 | 原 15 表 | 审计 |','|---:|---:|---:|---|---|---|']
for row in matrix:lines.append('| C'+str(row['configured_concurrency'])+' | '+str(row['actual_call_peak'])+' | 900/900 | '+('是' if row['read_build_overlap'] else '否；C1 原规范允许')+' | 15/15 相等 | ['+str(row['artifact_id'])+']('+row['review_file']+') |')
lines.extend(['','每档原始 transport 都保留了 301 次 index（初始 full 一次及 300 次 incremental）、600 次 workload symbol read 及一次终点 symbol read。独立 full control 仅执行一次，并在所有 workload 回包后启动；没有额外 incremental 修复。每档都有 50 次真实 branch switch、6 次 catalog compaction，原 raw 与统计双 replay 一致。调用峰值来自原记录和独立时间区间重算，不能用配置值替换。','','[Fake backfill 独立审计](backfill-11591821446-review.json) 覆盖原 3 seeds × quiet/held × C1/4/8/16 ×32＝768 次请求。原 2 秒 query、5 秒 progress 和 100 ms writer watchdog 未改变；每 seed provider 最大活跃 4、旧空间发布 0、最终 pending/claimed/uncovered 为 0。该原测试使用同进程 fake provider，没有 live-provider 或新 tail SLA 认证。','','这些分布按各自 profile、并发和 mutation stratum 分开；不把 3600 mixed 操作池化为一组尾延迟样本。原 build/mutation 的不可界定 CI 上界继续保留 null。P8-007 的原 P8-006 依赖及更广回归/验收仍须完成。','','## P8-008：原 lifecycle 分层','','[原 lifecycle run](https://github.com/jyqj/codecortex/actions/runs/37871838975) 与 [独立审计](lifecycle-11591607348-review-v2.json) 证实 30 cold、400 reopen、400 warm uncached、400 cache hit，1230/1230 success；另有一次不计样本的真实 warmup。431 个原生 product session 均正常关闭，1200 个 raw query witness 经原 Rust collector 源码核验；原 native evaluator 双 replay 字节完全一致。','','全部尝试和 CI 均保留。30 cold 的 p95/p99 CI 上界为 null；400 query 各层的原 CI 有界。OS page cache 未清理、仍 unknown；不能称 cold disk、稳定 p99 或性能提升。P8-008 仍保留原 P8-007 依赖。','','## P8-009：单位、归属和 unavailable','','1261 个原资源快照中，native client/server/process-tree 都有真实观测，采样 RSS 最大值依次为 149929984、33886208、33656832 bytes；server 与 tree 在不同采样时点，且前者包含在后者内，不能相加。client 的 ps 替代项及 external/LSP/OCE 为 unavailable，保持 null；它们不构成新增认证门。总 RSS、连续采样间隔也保持 null。stage snapshots 不能证明连续峰值或未采到的临时子进程。','','30 个闭合 cold fixtures 的 90 个唯一物理对象全部归 shared SQLite，合计 128901120 bytes；30 个零长度文件是原实际 stat=0 的对象。每 fixture 的逻辑 FTS pages 分别为 chunks 118784、file_paths 20480、files 36864、literal 20480、symbols 90112 bytes；它们已在 DB 物理字节中，不再加总。该物理账本包含 30 份 fixture，不是一份 active index footprint。','','原 artifact 逻辑长度快照为 343527625 bytes＝source 669540＋fixture storage 128901120＋raw/reports 213956965；记录点早于最后 receipt 写入，不能称完整 zip 或 allocated-disk 总量。费用 reported/estimated/input/output tokens/billed requests 全为 null，disabled provider 标为 not applicable；network filter 为 not_measured，不推断零账单。','','审计 v2 按“可用则核单位/归属，不可用则保留 null”复核；没有把原规范允许的 unknown 变成额外性能门。原 server CPU 使用纳秒，runner SELF 秒值保留秒单位；query CPU/IO delta 含前后 status 观察开销。','','## 待完成的原验收','','Soak job [113631481157](https://github.com/jyqj/codecortex/actions/runs/37871838957/job/113631481157) 于 2026-10-09 02:48:58 UTC 进入原 1 小时 workload。须等待真实终态，再核 3601 原操作、2400 次四 RPC 复合读取、四季度真实 cache hit/miss/invalidation、原 RSS 趋势与覆盖门、真实 compaction/切分支和无修复 15 表终点对账。现阶段没有 P8-010 完成结论。','','P8-011 还需独立原 failure-gates 和其 P7-020/P8-007/P8-010 依赖，不能由这组观测推断完成。','','Mac 端执行的是原件独立审查，包括原 Python source/observer/seal/cache/RSS/latency 等验证器，以及所有原 payload/计数/CI 的复核；原 Linux ELF collector 与原 GitHub Cargo target 没有在 Mac 重新执行。原 native workload、双 replay 与 oracle 由原 GitHub 日志、原 bytes 和 receipt 绑定。','','完整机器可读映射：[round4-p8-007-009-evidence-map.json](round4-p8-007-009-evidence-map.json)。'])
md=review/'round4-p8-007-009-review.md';md.write_text('\n'.join(lines)+'\n')
print(json.dumps({'done':163,'remaining':29,'new_todo_closures':0,'mixed_profiles':len(matrix),'mixed_samples_each':900,'backfill_requests':768,'lifecycle_samples':1230,'soak':'original_workload_in_progress','json':str(path),'markdown':str(md)},ensure_ascii=False))
