#!/usr/bin/env python3
import json,pathlib
O=pathlib.Path(__file__).resolve().parent
d=json.loads((O/'paired-decision.json').read_text());b=d['results']['baseline'];c=d['results']['candidate']
def fmt(x,n=3):return 'unknown' if x is None else f'{x:.{n}f}' if isinstance(x,float) else str(x)
def boundary(r):return r['boundary']['counts']['semantic_manifest'] if r['boundary'] and r['boundary'].get('counts') else 'unknown'
def last(r,actor='product'):return r['resources']['root_and_server_observations'][actor]['last']
def io(r,k):
 x=last(r);return x['io'].get(k) if x and x.get('io') else None
def delta(r,k):
 x=r['resources']['phase_counters'].get('backfill-drain',{}).get('product',{}).get('sampled_delta');return x['io'].get(k) if x else None
lines=['# FIFO 100k 单一预注册配对性能决策（2026-10-03）','',f"**性能接受：{d['performance_acceptance']}；生产集成：False。** {d['reason']}",'','仅一个顺序配对：baseline → candidate，各唯一一次。没有统计显著性结论。正确性另独立 review；证据 replay 只核验身份与留存。','', '| 指标 | baseline | candidate |','| --- | ---: | ---: |']
for name,x,y in [('源码 SHA',b['source_sha'],c['source_sha']),('binary SHA256',b['binary_sha256'],c['binary_sha256']),('cold 秒',fmt(b['cold_seconds'],6),fmt(c['cold_seconds'],6)),('300s 内 ready 秒',fmt(b['ready_seconds'],6),fmt(c['ready_seconds'],6)),('结果',b['status'],c['status']),('边界 semantic_manifest / 100000',boundary(b),boundary(c)),('边界快照开始 elapsed 秒',fmt(b['boundary'].get('elapsed_drain_seconds'),6) if b['boundary'] else 'not_run',fmt(c['boundary'].get('elapsed_drain_seconds'),6) if c['boundary'] else 'not_run'),('cleanup 尾段 semantic_manifest',b['cleanup_tail']['counts']['semantic_manifest'] if b['cleanup_tail'] else 'unknown',c['cleanup_tail']['counts']['semantic_manifest'] if c['cleanup_tail'] else 'unknown'),('cleanup 尾段 elapsed 秒',fmt(b['cleanup_tail']['elapsed_drain_seconds'],6) if b['cleanup_tail'] else 'unknown',fmt(c['cleanup_tail']['elapsed_drain_seconds'],6) if c['cleanup_tail'] else 'unknown'),('status 观察/错误',f"{b['status_observations']}/{b['status_errors']}",f"{c['status_observations']}/{c['status_errors']}"),('status latency p50/p95 ms',f"{fmt(b['status_latency_ms']['p50_ms'])}/{fmt(b['status_latency_ms']['p95_ms'])}",f"{fmt(c['status_latency_ms']['p50_ms'])}/{fmt(c['status_latency_ms']['p95_ms'])}"),('root sampled RSS max bytes',b['resources']['root_and_server_observations']['product']['sampled_max_rss_bytes'],c['resources']['root_and_server_observations']['product']['sampled_max_rss_bytes']),('root 最后可读 lifetime CPU user/system 秒',f"{fmt(last(b)['cpu_user_seconds'])}/{fmt(last(b)['cpu_system_seconds'])}" if last(b) else 'unknown',f"{fmt(last(c)['cpu_user_seconds'])}/{fmt(last(c)['cpu_system_seconds'])}" if last(c) else 'unknown'),('root 最后可读 lifetime write_bytes',io(b,'write_bytes'),io(c,'write_bytes')),('root 最后可读 lifetime rchar',io(b,'rchar'),io(c,'rchar')),('drain sampled write_bytes delta',delta(b,'write_bytes'),delta(c,'write_bytes')),('drain sampled rchar delta',delta(b,'rchar'),delta(c,'rchar'))]:lines.append(f'| {name} | {fmt(x)} | {fmt(y)} |')
lines+=['','计数为实际记录时间的近边界只读快照，不冒称精确 300.000000s。尾段在期限之外，不提升 ready 判定。正常 EOF 清理退出不能替代 gated post-ready normal-exit 检查。','', 'RSS 为 20ms 非原子采样。完整进程树在 children coverage 不可读时为 **unknown**；observable sum 不作为完整 tree RSS。CPU/IO 是最后可读累计计数或 phase 采样端点差，未知不填 0，不能当精确进程退出总量。read_bytes=0 也不表示没有读取工作。','']
for label,r in [('baseline',b),('candidate',c)]:
 lines += [f"{label}：not_run = `{json.dumps(r['not_run'])}`；failure cleanup exit = `{json.dumps(r['cleanup_exit'])}`。",'']
 if r['cleanup_tail']:
  lines += [f"{label} cleanup DB：`{json.dumps(r['cleanup_tail']['counts'],sort_keys=True)}`；integrity={r['cleanup_tail']['integrity']}，FK errors={r['cleanup_tail']['foreign_key_errors']}。",'']
 lines += [f"{label} HTTP：`{json.dumps(r['http'],sort_keys=True)}`。",'',f"{label} poll gap ms：`{json.dumps(r['poll_gap_ms'])}`。",'']
lines += ['协议完整保留 PR108 `99973e7d` 最终 run.py：100000 个确定性 Rust 文件，source(i,value=0)、128dims、release semantic+semantic-http、真实 MCP stdio、loopback 假 HTTP、cold → held DB 校验 → HTTP release → 300s ready deadline，claim16/concurrency4/per-project2/parse4，200ms poll gap，原 index/search RPC300s、EOF15s、overall900s、memory12GiB/disk4GiB guard。模型第一批请求 gate 与 120s fixture gate deadline 均未改。','', '两个 binary 在测量前全部构建完成，无测量期并行 build；fresh root/DB/cache，各自空 synthetic Git repo。source-inputs manifest、配置（包括固定 endpoint 端口）、静态环境核验完全一致。两版唯一生产差异是 FIFO SQL、partial pending index DDL、matching-v24 physical maintenance 三个文件；无临时 production probes。OS/page cache 未清理，顺序效应保留，cgroup current 包含 harness/build/page cache，不作产品 RSS。','', 'PR108 旧失败只作上下文，不作本次 baseline。PR114 原两组 5k ready 22.965/25.051 → 25.963/26.654s，物理写入约 +4.4%，此回归仍保留；claim 微基准或 100k partial count 增加都不单独构成通过。','', 'PR114 新测试 lint 修复 head `52a50730b58e2b59351449fc80f65771b24c26a8` 的 382 个生产/构建输入文件与冻结 candidate 字节一致；`lint-fix-production-identity.json` 单列此核验。未追新 head 构建/重跑，也不外推其测试身份。','', '证据：`preregistration.json`、`pair-builds-ready.json`、`source-identity.json`、`production-delta.patch`；`pr108-run.py`/`pr108-protocol.json` 与逐版 derivation patches；各版 build receipt、compressed Cargo/resource/RPC/HTTP/input logs；独立 deadline DB / cleanup tail DB；`extended-analysis.json`、`paired-decision.json`、`verification.json`；`compare.py` 可重放，`SHA256SUMS` 为 curated 留存清单。','', '生成 corpus、DB/cache、release binaries 和编译目录保留在该 checkpoint 下本地 runtime/live，排除 Git；`retained-local-data.json` 记录占用。所有任务文件仅写入本目录；生产、中央 ledger/CI/DEV/heldout 均未修改。没有真实 provider、GC/WAL kill/crash/fault、RO 拒写重试、权限/credential 变更、merge/forcepush/deploy。','', '阶段结论先报告父任务，再仅 commit/push/draft PR，并核验 exact remote 和文件范围；交付完即停。']
(O/'README.md').write_text('\n'.join(lines)+'\n')
print('README generated')
