pub(crate) mod community;
pub(crate) mod config_linker;
pub(crate) mod dispatch_synthesis;
pub mod framework_registry;
pub mod framework_resolvers;
pub(crate) mod git_cochange;
pub(crate) mod hierarchy;
pub mod indexer;
mod indexer_phases;
pub(crate) mod infra_docker;
pub(crate) mod infra_k8s;
pub(crate) mod infra_pass;
pub(crate) mod infra_terraform;
pub(crate) mod memory_budget;
pub(crate) mod resolver;
pub mod scanner;
pub(crate) mod type_catalog;

pub use framework_registry::FileFrameworkDetection;
pub use indexer::{IndexReport, Indexer};
pub use scanner::{ScannedFile, Scanner};
