import pathlib,json
O=pathlib.Path(__file__).resolve().parent
read=lambda p:json.loads(p.read_text())
d=read(O/'paired-decision.json');a=read(O/'supplemental-analysis.json');b=d['results']['baseline'];c=d['results']['candidate']
def fmt(v):return 'unknown / not_run' if v is None else f'{v:.6f}' if isinstance(v,float) else str(v)
def boundary(r):return r.get('boundary',{}).get('counts',{}).get('semantic_manifest') if r.get('boundary') else None
def end(r):return r['resources']['root_and_server_observations']['product']['last']
def io(r,k):return end(r)['io'].get(k) if end(r) else None
lines=['# Parallel + startup 原协议 100k 单次配对性能验收','',f"**硬 gate：baseline ready={b['readiness_pass']}；candidate ready={c['readiness_pass']}。性能接受={d['performance_acceptance']}。**",'',d['reason'],'','本任务只运行 baseline → candidate 各一次。单次配对不宣称统计显著；正确性由父任务独立审阅，本证据不重复认证。','', '| 项目 | baseline | candidate |','| --- | ---: | ---: |']
metrics=[('固定 source/head',b['source_sha'],c['source_sha']),('实际 Rust source',b['production_sha'],c['production_sha']),('binary SHA256',b['binary_sha256'],c['binary_sha256']),('cold 完整秒',b['cold_seconds'],c['cold_seconds']),('300s 内 ready 秒',b['ready_seconds'],c['ready_seconds']),('cold + ready 秒',b['cold_plus_ready_seconds'],c['cold_plus_ready_seconds']),('协议结果',b['status'],c['status']),('300s deadline 附近 semantic_manifest / 100000',boundary(b),boundary(c)),('deadline 只读快照开始 drain elapsed 秒',b['boundary']['elapsed_drain_seconds'] if b['boundary'] else None,c['boundary']['elapsed_drain_seconds'] if c['boundary'] else None),('cleanup tail semantic_manifest',b['cleanup_tail']['counts']['semantic_manifest'],c['cleanup_tail']['counts']['semantic_manifest']),('cleanup tail drain elapsed 秒',b['cleanup_tail']['elapsed_drain_seconds'],c['cleanup_tail']['elapsed_drain_seconds']),('status 观察 / 错误',f"{b['status_observations']} / {b['status_errors']}",f"{c['status_observations']} / {c['status_errors']}"),('status p50 / p95 ms',f"{b['status_latency_ms']['p50_ms']:.3f} / {b['status_latency_ms']['p95_ms']:.3f}",f"{c['status_latency_ms']['p50_ms']:.3f} / {c['status_latency_ms']['p95_ms']:.3f}"),('HTTP 原 fixture observed peak active',a['baseline']['http_observed_peak_active_intervals'],a['candidate']['http_observed_peak_active_intervals']),('root sampled RSS max bytes',b['resources']['root_and_server_observations']['product']['sampled_max_rss_bytes'],c['resources']['root_and_server_observations']['product']['sampled_max_rss_bytes']),('root 最后可读 lifetime CPU user / system 秒',f"{end(b)['cpu_user_seconds']} / {end(b)['cpu_system_seconds']}",f"{end(c)['cpu_user_seconds']} / {end(c)['cpu_system_seconds']}"),('root 最后可读 lifetime write_bytes',io(b,'write_bytes'),io(c,'write_bytes')),('root 最后可读 lifetime rchar',io(b,'rchar'),io(c,'rchar'))]
for name,x,y in metrics:lines.append(f'| {name} | {fmt(x)} | {fmt(y)} |')
lines+=['','## 协议与身份','', '正式原文及运行脚本来自 PR116 9a4f97877f1b18af77013f7bed7cd047994e26f3 和 PR108 99973e7d6faf3809add4a12cd444f8e69f04d93c，保留在 reference/ 并列 SHA256。100000 个确定性 source(i,value=0) Rust 文件，128dims，claim16，config global4/perproject2，parse4；cold → held DB → release loopback HTTP → ready 300s 硬截止 → 原查询/并发/正常 EOF/reopen。轮询 gap .2s；index/search RPC300s，正常 EOF15s，overall900s，fixture gate120s；memory12GiB/disk reserve4GiB。配置、语料和静态环境配对完全一致。', '', '两版均原 Cargo.lock/manifests，官方现成 Rust 1.95.0 direct bin，独立 fresh Cargo cache/target，locked release --no-default-features --features semantic-http；Cargo receipt 核实 semantic + semantic-http、opt3、debug_assertions=false。全部构建在首次测量前完成，测量前扫描未见编译进程。独立空 synthetic repo、DB/cache；未清 OS/page cache，保留 baseline-first 顺序效应。', '', '候选固定 ee8c578/source11f5b762，测前测后 root HEAD、工作树和输入 hash 无漂移，主工作树初始 ff458bc 保持产品只读。父通知 PR123 后续 513a98c 是 TODO 文档同步、Rust/SQL/Cargo/lock 字节未变；该关系按父通知记录，未跟随其 head 或增加样本。', '', 'baseline 旧 service_factory 为 OnceLock first-wins；候选为显式 caps 可采用且冲突/busy 报错的共享 gate。配置4/2并不直接证明运行时 effectivecaps；两版原 status 均未暴露 semantic provider gate caps，因此 effective_caps_runtime_directly_observable=false，global/per_project 有效 cap 均为 unknown。observed_execution_counters_in_last_status 仅为 query execution pool counters/limits，不是 semantic gate caps；此前将 in_flight 关键字匹配误作 gate cap 观测，已在证据修正中纠正。本协议显式 --project-path 路径的源码推断为 baseline 先 init4/2 后 getter，并非必然触发 permissive first-wins；详见 gate-source-observation.json。源码路径说明与 HTTP interval 观测分别留存，未注入生产修正或探针；HTTP 并发来自原 entered/returned 日志，不能替代直接 gate snapshot。候选 observed interval peak3仅出现在两个窗口、总约2.419ms：原 fixture 在 response write 后才记录 returned，客户端可能先收到响应释放 permit，再由新请求 entered；因此 peak3不是 gate perproject2 被违反的证明。见 http-concurrency-windows.json。','', '## 分版阶段与资源','']
for label,r in [('baseline',b),('candidate',c)]:
 lines+=[f"### {label}",'',f"not_run：`{json.dumps(r['not_run'])}`。post-ready normal_exit 实际运行：`{r['post_ready_normal_exit_check']}`；exits：`{json.dumps(r['process_exits'])}`；失败 cleanup exit：`{json.dumps(r['cleanup_exit'])}`。",'',f"failure：`{json.dumps(r['failures'],ensure_ascii=False)}`。",'',f"HTTP 按 release/deadline 分期：`{json.dumps(r['http'],sort_keys=True)}`。",'',f"HTTP concurrency：`{json.dumps(a[label],ensure_ascii=False)}`。",'',f"poll gap ms：`{json.dumps(r['poll_gap_ms'])}`。",'',f"cleanup tail DB：`{json.dumps(r['cleanup_tail'],ensure_ascii=False)}`。",'',f"资源 phase counters 与 sampled RSS：见 `{label}/extended-analysis.json` / `{label}/resource-analysis.json`。CPU/IO 是最后可读累计值或 phase 采样端点差，未知不补0；read_bytes=0 不代表没有读取。",'']
lines+=['## 解释边界与留存','', 'HTTP request_enter_gap_ms 现在按 entered.time_ns 排序后计算。候选原 append 顺序有一次 timestamp inversion，最小 signed gap -2.713795ms；原 fixture 在 logging lock 前采样 entered timestamp，在锁内分配 sequence/追加，所以 append 顺序不等于时间戳顺序。原 signed 值保留为 request_enter_gap_append_order_diagnostic_ms，仅用于诊断日志顺序；不解释成负到达间隔。此时间戳晚于 body read，排序结果也不是 socket arrival spacing。raw 日志未改。', '', 'deadline 快照是独立只读 SQLite observation，保留实际 query/read 时间；未冒称恰好300.000000s。超过 deadline 的响应不接受为 ready，失败 tail 的额外 manifest 不变成通过。失败 EOF cleanup 与 post-ready 正常退出分开。正常 API EOF 和 integrity/FK 检查不构成 GC/WAL crash 证明。', '', 'RSS 为原20ms非原子采样，不是精确峰值/PSS。children 不可读则完整进程树 RSS unknown；observable sum 不冒充 full tree。cgroup current 包含 harness、build及page cache，不作产品 RSS。首次 Product 和 reopen 的原 raw resource logs 均保留；主表 lifetime 值描述首次 Product，reopen logs 单列，不合并不同 PID 的 lifetime counters。', '', '无真实/付费 provider、heldout、GCWAL kill/crash/fault、EROFS testcase 或宽泛 runtime 组；无 fsync/cachelayout/SQL/预算/产品/CI 修改或循环调参。build/measurement 每项一次，历史失败只读保留。', '', 'source-identity.json、reference-hashes.json、逐版 derivation.patch、build receipt、pair-builds-ready.json、pair-execution.json、compressed input/resource/RPC/HTTP logs、deadline/cleanup snapshots、verification.json、supplemental-analysis.json、paired-decision.json 与 SHA256SUMS 是本次证据。compare.py / supplement.py 可只读重放；runtime/live repo/cache/targets 本地留存，Git 排除。', '', '交付授权为本目录证据 commit/push/draft PR及远端验证；不 merge/forcepush/deploy。结果与真实访问阻塞先报告，交付完成即停。']
(O/'README.md').write_text('\n'.join(lines)+'\n')
print('report written')

(O/'README.md').open('a').write('\n交付：Draft PR https://github.com/jyqj/codecortex/pull/124；初始证据 commit f2841d43cebf49c57a4c5305bbad907fc881ba97。此次仅纠正 derived gate cap observability 与 HTTP timestamp 排序解释，不新增测量，硬 gate 失败结论不变。\n')
