from pathlib import Path
import json,hashlib,copy,datetime
root=Path('/workspace/scratch/bfccb8494ba0');out=root/'round40-fresh45-dependent-application-preparation'
def load(p):return json.loads((root/p).read_text())
def identity(p):
 p=Path(p);b=p.read_bytes();return dict(path=str(p),bytes=len(b),sha256=hashlib.sha256(b).hexdigest(),git_blob=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest())
def write(name,x):
 p=out/name;assert not p.exists();p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n');return p
oldpath='round37-nine-task-application-revision/nine-task-dependent-update-input.applyfalse.v2.json';old=load(oldpath)
postpath='round39-post-nine-addendum/post-nine-baseline-addendum.applyfalse.json';post=load(postpath)
protocolpath='round40-task-descriptive-driver-candidate/candidate/docs/roadmap/code-index-v2/p8-profile-task-descriptive-v1.json';protocol=load(protocolpath)
assert (protocol['cell_count'],protocol['record_count'],protocol['repetitions'])==(45,85,1)
j=copy.deepcopy(old);j['schema']='nine-dependent-application-input-fresh45-descriptive-route-v1';j['prepared_at_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();j['append_only_basis']={'previous_nine_input':identity(root/oldpath),'previous_post_nine_input':identity(root/postpath),'failed_old_route_notice_blob':'22c030a9b4b1e2888c2b68f52d267d250aa8f216','old_files_unchanged':True,'new_source_scope_review_actual_blob':'8adf965b33663cb72c138d3db69dce58142df0a7','protocol_source_file':identity(root/protocolpath),'not_an_old_study_amendment':True}
j['selected_future_route']={'schema':protocol['schema'],'stage_scope':protocol['stage_scope'],'actual_P':None,'actual_R':None,'actual_G':None,'actual_tree':None,'actual_workflow':None,'actual_registration':None,'actual_build':None,'run_id':None,'run_attempt':None,'execution_date':None,'actual_CI':None,'accepted_cells':0,'accepted_observations':0,'expected_cells':45,'expected_observations':85,'required_actual_task_decision':None}
j['old_route_disposition']={'source':'9cc6bf49f6dd81e4069a8004eed49addba0ab79b','run_id':38013753078,'attempt':1,'study_population':{'shards':150,'observations':1500,'N':30},'accepted_original_shards':4,'accepted_original_observations':41,'100k_job':{'id':114100438875,'conclusion':'failure','completed_at':'2026-10-10T03:54:45Z','native_cause':'unknown_from_retained_artifacts'},'aggregate':'failure','later145':'skipped','not_complete_five_rep0_route':True,'negative_evidence_notice_blob':'22c030a9b4b1e2888c2b68f52d267d250aa8f216','old_new_pooling_forbidden':True,'other_original_N30_and_failed_runs_preserved':True,'independent_diagnostic_credit':0}
u=j['updates'][0];assert u['task_id']=='P8-006'
u['accepted_own_scope_state']='new_independent_protocol_source_reviewed; actual_new_source_CI_build_run_and_all45_original_cells_pending'
u['remaining_original_own_scope_actions']=['Bind actual immutable P/R/G/workflow and ordinary CI/source-compatibility evidence; source-only review is not execution.','Before measurement, retain the actual source/build/binary/observer/run/attempt-bound task-registry.json with all45 exact plans; every original cell is required.','Accept all45 unique original cells and all85 records:40 setup pairs,40 selected mutation observations,5 fanout observations; retain complete raw/output/reports and all failures.','Use actual phase/build counts, full initial/final15-table parity, original independent facts and actual over-budget incomplete-to-closure witness; report N1 per scale/profile/fanout and host environment.','Bind the complete original custody/aggregate and independent actual P8-006 task decision plus V07/related old-regression applicability and already-required dependencies. No task change until these inputs exist.','Preserve original150/1500/N30 and donor1350/N30 studies and every historical failure under their own identities; new45 cannot fill or relabel their slots.']
evidence={'date':None,'status':None,'selected_source':None,'selected_profile':'profile_task_descriptive_v1','run_id':None,'run_attempt':None,'actual_P':None,'actual_R':None,'actual_G':None,'actual_build_receipt':None,'actual_preregistered_task_registry':None,'actual_complete_45_cell_catalog':None,'actual_original_task_aggregate':None,'complete_custody_locator':None,'phase_accounting':None,'full15table_parity_and_incomplete_to_closure':None,'related_regression_evidence':None,'source_compatibility_disposition':None,'actual_current_source_CI':None,'actual_task_acceptance_receipt':None,'actual_dependency_closeout_locators':{'P7-020':None,'P8-001':None,'P8-005':None},'registered_population':{'cells':45,'measurement_records':85,'setup_records':40,'mutation_records':40,'fanout_records':5,'repetitions_per_group':1},'actual_accepted_cells':None,'actual_accepted_measurement_records':None,'scope':'Original P8-006 descriptive task coverage using a separately preregistered fresh-history population. No stable-tail, pooled-host speedup, statistical significance, complete old150/1500 or1350, wholeV20 orG8 release pass.','cold_curve_selection':'Only no_op setup at each of5 scales is the preselected descriptive cold point; retain other35 setups without pooling as coldN8. No new005 credit.','fanout_file_scope':'Actual fanout1/4/16/64/128 uses N+1 files; native files1000 is only the capacity-reservation field.','other_studies_preserved_separately':True,'optional_metrics':'Missing/unavailable/disabled measurements remain null or explicitly unavailable, never fabricated0.'}
u['conditional_patch']['append_evidence']=evidence;u['conditional_patch']['append_implementation_notes']=None
u['implementation_notes_candidate_text_not_applied']='待实际新独立profile_task_descriptive_v1完成45/45单元与85/85原观测、完整原始验收及正式任务评审后，按八个fresh mutation profiles×五scale和五fanout记录闭合原006工作范围。每格保留fresh A/B初始与最终15表parity、全部continuations、阶段计数、独立配置/调用边真值及实际超预算incomplete→complete证据。N=1逐profile/scale/fanout与host描述，不声称连续旧history性能、稳定尾部、跨环境因果或G8通过。旧G9cc6 run38013753078的100k失败、aggregate失败、145skipped与4/150、41/1500已接受前缀全部留存；新45不填旧队列，也不改PR192原1350/N30。补齐实际日期/源/运行/完整custody、CI与正式006决定后才可append；本候选当前不应用。'
j['future_006_receipt_required']={'actual_now':None,'required_nonnull_before_setting_done':['date','status','selected_source','run_id','run_attempt','actual_P','actual_R','actual_G','actual_build_receipt','actual_preregistered_task_registry','actual_complete_45_cell_catalog','actual_original_task_aggregate','complete_custody_locator','phase_accounting','full15table_parity_and_incomplete_to_closure','related_regression_evidence','source_compatibility_disposition','actual_current_source_CI','actual_task_acceptance_receipt','actual_dependency_closeout_locators.P7-020','actual_dependency_closeout_locators.P8-001','actual_dependency_closeout_locators.P8-005','actual_acceptance_review','actual_application_base','actual_application_date'],'exact_population_required':{'accepted_cells':45,'accepted_observations':85,'all_registered_slots_unique':True,'all_original_predicates_passed':True},'not_substitutes':['newsource static review','debug tests rejectingRelease','upload/CRC success alone','sourceguard0 alone','old4rep0 prefix','independent diagnostic or captured prefix','oldPR192 engineering tests or old1350 scope'],'not_a_waiver':'The new protocol itself is frozen before execution and requires all45. No outcome-based deletion/replacement/mixedsource or sampling change; original studies remain unmodified.'}
j['actual_apply_procedure'][1]='Stop while any required fresh45 identity/build/registry/original acceptance,45/85 complete catalog+aggregate, relevant CI/source bridge, or formal006 decision is null or rejected. This template is not that decision.'
j['actual_apply_procedure'][3]='For007–013/016 retain all inherited source_and_run_refs and original dependencies unchanged. Fill actual final acceptance/date/dependency-closeout locators; no blanket latestsource rerun or cohort migration.'
j['excluded_post_nine_scope']='017–019 remain a separate conditional wave. P8-018 original baseline now has actualrun38020782259 exit0 with three preserved historicalDRIFT lines; inherited round39 addendum carries this fact, no newnoDRIFT gate.'
assert j['updates'][1:]==old['updates'][1:]
for key in ['source_component_index','permitted_task_fields','forbidden_changes','original_commands','updated_files','derived_views','ordered_original_ids','ordered_counts']:
 assert j[key]==old[key],key
write('nine-task-fresh45-route.applyfalse.json',j)
postlink={'schema':'post-nine-017-019-conditional-route-link-v1','apply_now':False,'current_counts':{'done':164,'remaining':28,'session_completed':1},'source_post_nine_input':identity(root/postpath),'source_post_nine_input_actual_blob':'aa289172d782c0fae0a6872005452ad99b30f7c4','own_scope_and_prior_execution_records':copy.deepcopy(post['future_task_updates']),'baseline_current_evidence':{'actual_run_id':38020782259,'attempt':1,'exit_code':0,'historical_DRIFT_count':3,'actual_review_blob':'565e1c18e24a382c43f18f8bf9ecef8873d4b4d0','independent_peer_blob':'c1a9c241793a4c29e411249a5ea0af6dbca56462','historical_TEST_PLAN_not_refreshed':True},'formal_decisions':{'P8-017':None,'P8-018':None,'P8-019':None},'future_application_date':None,'future_actual_source_base':None,'conditions':['Nine preceding tasks must genuinely close under their unchanged original definitions and dependency evidence.','Reuse the recorded own-scope proofs with their original source/run identities; append a bounded current-source applicability bridge where the final implementation differs, not blanket reruns.','Each017→018→019 still needs its own original hard dependency done and a real final task decision; this preparation alone supplies neither.','Baseline actual0 and3historicalDRIFT fill the previously unexecuted contribution-script record, not whole-release or statistics certification.','The future evidence target/application source is actual futuremain; all embedded b9/earlier targets remain historical execution identities.'],'conditional_counts':[{'after':'nine','done':173,'remaining':19,'session_completed':10},{'after':'P8-017','done':174,'remaining':18,'session_completed':11},{'after':'P8-018','done':175,'remaining':17,'session_completed':12},{'after':'P8-019','done':176,'remaining':16,'session_completed':13}],'tasks_modified':False}
write('post-nine-017-019-route-link.applyfalse.json',postlink)
# Read the retained official PR object; no new network or branch observation.
def unwrap(x):
 for _ in range(9):
  if isinstance(x,str):x=json.loads(x)
  elif isinstance(x,dict) and 'response'in x:x=x['response']
  elif isinstance(x,dict) and 'structuredContent'in x:x=x['structuredContent']
  elif isinstance(x,dict) and isinstance(x.get('content'),str):x=x['content']
  else:return x
 return x
pr=unwrap(load('round40-PR192-profile-isolation-review/pull.official-original.json'));files=unwrap(load('round40-PR192-profile-isolation-review/files.official-original.json'))
artifacts=[{'path':x['filename'],'git_blob':x['sha'],'status':x['status']} for x in files if x['filename'].startswith('artifacts/')]
bindings=[{'path':x['filename'],'git_blob':x['sha'],'status':x['status']} for x in files if x['filename'] in ['scripts/reviewed-source-registry-v15.json','scripts/verify_reviewed_source_v15.py']]
assert len(files)==34 and len(artifacts)==22 and len(bindings)==2
basis=load('round40-PR192-main-integration-candidate/source-manifest.json');v2=load('round40-profile-task-descriptive-native-candidate/v2/source-manifest.json');after={x['path']:x['after'] for x in v2['files']};rows=[]
for f in basis['files']:rows.append(dict(path=f['path'],old_PR_status=f['status'],donor=f['donor'],main_before=f['before'],integrated_base=f['after'],new_final_candidate=after.get(f['path'],f['after']),disposition='donor exact bytes retained' if f['status']=='A' else 'exact common-base three-way integration retains donor behavior and main wide; new named scope is an explicit further delta'))
relationship={'schema':'pr192-source-successor-and-history-disposition-v1','read_only':True,'source_observation':{'pull':identity(root/'round40-PR192-profile-isolation-review/pull.official-original.json'),'files':identity(root/'round40-PR192-profile-isolation-review/files.official-original.json'),'not_fresh_PR_state_claim':True},'original_PR':{'number':192,'head':pr['head']['sha'],'base':pr['base']['sha'],'state_at_observation':pr['state'],'merged_at_observation':pr['merged'],'changed_paths':34},'source_accounting':rows,'preserved_artifact_leaves_at_original_head':artifacts,'historical_bindings_not_copied_into_new_source':bindings,'artifact_directory_locators':['https://github.com/jyqj/codecortex/tree/'+pr['head']['sha']+'/artifacts/checkpoints/p8-profile-format-repair-a217-20261009','https://github.com/jyqj/codecortex/tree/'+pr['head']['sha']+'/artifacts/checkpoints/p8-profile-isolated-source-a217-20261009'],'new_actual_product_commit':None,'new_actual_successor_PR':None,'new_actual_main_merge':None,'can_claim_now':['Ten source paths are accounted for in the reviewed candidate; original five additions retain exact donor bytes.','OldN30/1350 protocol is preserved and is not redefined as45.','Original source/review/CI/failure22artifact leaves and twooldbinding identities remain separately addressed at e7f8.'],'cannot_claim_now':['All34 donor leaves merged into currentmain.','The new source has passed actualCI/native45.','PR192 or its1350 study contributed newtask observations.'],'supersession_conditions':['Fresh-read PR192 head before action; if changed frome7f8, first account only for the newdelta.','Identify an actual durable successorcommit andPR containing these ten integrated source paths plus the separately reviewed newscope; compare exact finaltree/paths.','Preserve the original e7f8 history and22artifact directory locators and recorded failures/CI; do not copy oldP/R pins onto newsource.','Root may close originalPR as replaced after durable reviewed successor handoff, clearly stating whether successorCI/merge remain pending; this is not product/runtime/task acceptance.','To say alreadyintegratedintomain, first cite the actual successor merge and exactsource bridge. Full1350 or45 execution is not a PRsupersession prerequisite and receives no credit from closure.'],'recommended_current_action':'Keep pending until root supplies actual successoridentity. No close/comment/ref action performed.'}
write('PR192-successor-conditions.readonly.json',relationship)
summary={'schema':'fresh45-application-preparation-delta-summary-v1','apply_now':False,'old_eight_updates_exact':True,'old_source_component_index_exact':True,'original_definition_hashes_and_dependencies_preserved':True,'changed_application_route_only':'P8-006 future evidence request switches to separately preregistered full45/85; failedfive-rep0 route stays retained, not salvaged.','all_future_P_R_G_run_date_and_006_decision_null':True,'counts_unchanged_now':{'done':164,'remaining':28,'session_completed':1},'conditional_after_nine':{'done':173,'remaining':19,'session_completed':10},'conditional_after_post_nine':{'done':176,'remaining':16,'session_completed':13},'old_protocol_N30_150_1500_1350_unchanged':True,'new_tests_generators_validators_workloads_network_reads':False,'actual_tasks_refs_PRs_modified':False}
write('append-only-difference-summary.json',summary)
selection=[]
for p in sorted(out.iterdir()):
 if p.is_file():selection.append(identity(p))
write('archive-selection.json',{'files':selection,'purpose':'small append-only application inputs and read-onlyPR relation, not originalstudy archives'})
print(json.dumps({'outputs':[(p.name,p.stat().st_size) for p in out.iterdir() if p.is_file()],'current_apply':False,'old8_equal':True}))
