use crate::ParserTier;
use serde::{Deserialize, Serialize};

/// Symbol kind — replaces string constants from Python version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SymbolKind {
    Function,
    Class,
    Method,
    Variable,
    Constant,
    Interface,
    TypeAlias,
    Enum,
    Module,
    Namespace,
    Property,
    Export,
    Hook,
    Component,
    Middleware,
    Controller,
    RouteHandler,
    Route,
}

impl SymbolKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Function => "function",
            Self::Class => "class",
            Self::Method => "method",
            Self::Variable => "variable",
            Self::Constant => "constant",
            Self::Interface => "interface",
            Self::TypeAlias => "type_alias",
            Self::Enum => "enum",
            Self::Module => "module",
            Self::Namespace => "namespace",
            Self::Property => "property",
            Self::Export => "export",
            Self::Hook => "hook",
            Self::Component => "component",
            Self::Middleware => "middleware",
            Self::Controller => "controller",
            Self::RouteHandler => "route_handler",
            Self::Route => "route",
        }
    }

    /// Parse from string (lenient — returns None for unknown kinds).
    pub fn from_str_lenient(s: &str) -> Option<Self> {
        match s {
            "function" => Some(Self::Function),
            "class" => Some(Self::Class),
            "method" => Some(Self::Method),
            "variable" | "var" | "let" | "const" => Some(Self::Variable),
            "constant" => Some(Self::Constant),
            "interface" => Some(Self::Interface),
            "type_alias" | "type" => Some(Self::TypeAlias),
            "enum" => Some(Self::Enum),
            "module" => Some(Self::Module),
            "namespace" => Some(Self::Namespace),
            "property" => Some(Self::Property),
            "export" => Some(Self::Export),
            "hook" => Some(Self::Hook),
            "component" => Some(Self::Component),
            "middleware" => Some(Self::Middleware),
            "controller" => Some(Self::Controller),
            "route_handler" => Some(Self::RouteHandler),
            "route" => Some(Self::Route),
            _ => None,
        }
    }
}

impl std::fmt::Display for SymbolKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A symbol definition extracted from source code.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolRecord {
    pub symbol_id: String,
    pub file_path: String,
    pub name: String,
    pub kind: SymbolKind,
    pub container: Option<String>,
    pub start_line: u32,
    pub end_line: u32,
    pub start_col: u32,
    pub end_col: u32,
    pub signature: Option<String>,
    pub doc: Option<String>,
    pub parser_tier: ParserTier,
    pub parser_confidence: f64,
    pub qname: Option<String>,
    pub parent_symbol_id: Option<String>,
    pub scope_id: Option<String>,
    pub export_name: Option<String>,
    pub is_default_export: bool,
    /// Stable UID generated by `StableId::symbol_uid()`
    pub symbol_uid: Option<String>,
    /// Framework-specific role (e.g., "hook", "controller", "middleware")
    pub framework_role: Option<String>,
    /// Receiver type for methods (e.g., "MyStruct", "*http.Client")
    pub receiver_type: Option<String>,
    /// Parameter types as comma-separated string (e.g., "string, int, bool")
    pub param_types: Option<String>,
    /// Return type (e.g., "error", "Promise<string>")
    pub return_type: Option<String>,
    /// Number of parameters (for overload resolution)
    pub param_count: Option<u32>,
    /// Base types this type extends/embeds (comma-separated)
    pub base_types: Option<String>,
    /// Interfaces/traits this type implements (comma-separated)
    pub implements: Option<String>,
}

/// A symbol reference (usage site).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymbolRefRecord {
    pub ref_id: String,
    pub file_path: String,
    pub symbol_name: String,
    pub container: Option<String>,
    pub ref_kind: String,
    pub line: u32,
    pub column: u32,
    pub target_symbol_id: Option<String>,
    pub target_file_path: Option<String>,
    pub target_symbol_uid: Option<String>,
    pub ref_name: Option<String>,
    pub scope_id: Option<String>,
    pub resolution_kind: crate::edge::ResolutionKind,
    /// Fine-grained resolver confidence (distinct from parser confidence).
    pub resolution_confidence: f64,
    /// Fine-grained resolution strategy name (e.g. exact/import_map/global_unique).
    pub resolution_strategy: String,
    pub ref_end_line: Option<u32>,
    pub ref_end_col: Option<u32>,
    pub parser_tier: ParserTier,
    pub parser_confidence: f64,
}
