//! Fixed local FakeProvider experiment using actual production status source.
mod service_factory {
    pub use cc_server::service_factory::SemanticWiredInfo;
    pub struct QueryServices(pub std::sync::Arc<cc_server::service_factory::QueryServices>);
    impl std::ops::Deref for QueryServices {
        type Target = cc_server::service_factory::QueryServices;
        fn deref(&self) -> &Self::Target { &self.0 }
    }
    impl QueryServices {
        pub fn query_encoding_active(&self) -> bool {
            panic!("network permission gates must short circuit in this offline fixture")
        }
    }
}
#[path = "../../../../../crates/cc-server/src/capability_status.rs"]
mod candidate_status;
mod baseline_status;
use cc_semantic::{ports::{DocumentInput, EmbeddingProvider, ProviderError, QueryInput},
    providers::fake::{FakeProvider, FakeProviderConfig}};
use std::{sync::{Arc, Condvar, Mutex, atomic::{AtomicUsize, Ordering}}, time::{Duration, Instant}};
use serde_json::json;
struct Gated {
    inner: FakeProvider,
    first: Mutex<Option<tokio::sync::oneshot::Sender<()>>>,
    gate: Arc<(Mutex<bool>, Condvar)>,
    calls: AtomicUsize,
    inputs: AtomicUsize,
}
impl EmbeddingProvider for Gated {
    fn space(&self) -> &cc_semantic::types::VectorSpace { self.inner.space() }
    fn embed_documents(&self, inputs: &[DocumentInput]) -> Result<Vec<Vec<f32>>, ProviderError> {
        self.calls.fetch_add(1, Ordering::SeqCst);
        self.inputs.fetch_add(inputs.len(), Ordering::SeqCst);
        if let Some(tx) = self.first.lock().unwrap().take() {
            tx.send(()).unwrap();
            let deadline = Instant::now() + Duration::from_secs(10);
            let mut released = self.gate.0.lock().unwrap();
            while !*released {
                assert!(Instant::now() < deadline, "fixture gate timeout");
                released = self.gate.1.wait_timeout(released, Duration::from_millis(2)).unwrap().0;
            }
        }
        self.inner.embed_documents(inputs)
    }
    fn embed_queries(&self, _: &[QueryInput]) -> Result<Vec<Vec<f32>>, ProviderError> {
        panic!("document backfill fixture must not encode queries")
    }
}
#[tokio::main(flavor = "multi_thread", worker_threads = 2)]
async fn main() {
    let args = std::env::args().collect::<Vec<_>>();
    let mode = &args[1];
    assert!(mode == "baseline" || mode == "candidate");
    let n: usize = args[2].parse().unwrap();
    assert!([1000,5000].contains(&n));
    let out = std::path::PathBuf::from(&args[3]);
    std::fs::create_dir_all(&out).unwrap();
    // Independent cold temp root/cache each process; identical generated bytes.
    let root = tempfile::tempdir().unwrap();
    let mut config = cc_model::config::ProjectConfig::default();
    config.auto_index.enabled = false;
    config.indexing.db_read_pool_size = Some(1);
    config.semantic.enabled = true;
    config.semantic.network_opt_in = false;
    config.semantic.allow_query_network = false;
    config.semantic.model_id = "fake/capability-snapshot-ab".into();
    config.semantic.dimensions = Some(2);
    config.semantic.max_input_tokens = Some(8192);
    config.semantic.max_batch_items = Some(16);
    config.semantic.endpoint = "https://semantic.invalid/v1".into();
    std::fs::write(root.path().join(".codecortex.json"), serde_json::to_vec(&config).unwrap()).unwrap();
    for i in 0..n {
        std::fs::write(root.path().join(format!("file_{i:05}.rs")),
            format!("pub fn resource_{i:05}() -> u32 {{ {i} }}\n")).unwrap();
    }
    let mut index = cc_server::engine::CodeIndex::new(Some(root.path())).unwrap();
    let build_start = Instant::now();
    index.build_index(false).unwrap();
    let build_ms = build_start.elapsed().as_secs_f64()*1000.0;
    let db = index.index_db().unwrap().clone();
    let services = Arc::new(cc_server::service_factory::QueryServices::default());
    let subsystem = Arc::new(cc_server::semantic_wiring::assemble_with(
        &root.path().to_string_lossy(), &config, db.clone(),
        |key| (key == cc_semantic::cache::CACHE_ROOT_ENV)
            .then(|| root.path().join("cache").to_string_lossy().into_owned()), false,
    ).unwrap().unwrap());
    services.set_semantic(Some(subsystem.recall.clone()));
    services.set_semantic_wired(Some(cc_server::service_factory::SemanticWiredInfo {
        model_id: subsystem.space.model_id().to_owned(),
        dimensions: subsystem.space.dimension(),
    }));
    let (tx, rx) = tokio::sync::oneshot::channel();
    let gate = Arc::new((Mutex::new(false), Condvar::new()));
    let provider = Arc::new(Gated {
        inner: FakeProvider::new(FakeProviderConfig::new(subsystem.space.clone())),
        first: Mutex::new(Some(tx)), gate: gate.clone(), calls: AtomicUsize::new(0), inputs: AtomicUsize::new(0),
    });
    let worker = cc_server::semantic_runtime::SemanticRuntime::new(db.clone(), subsystem, services.clone(), provider.clone()).unwrap();
    assert!(worker.schedule());
    tokio::time::timeout(Duration::from_secs(10), rx).await.unwrap().unwrap();
    let wrapper = service_factory::QueryServices(services);
    let call_status = || if mode == "baseline" {
        baseline_status::snapshot(Some(root.path()), Some(&db), Some(&config), &wrapper)
    } else {
        candidate_status::snapshot(Some(root.path()), Some(&db), Some(&config), &wrapper)
    };
    let initial = call_status();
    assert_eq!(initial["retrieval"]["semantic_state"], "backfilling");
    assert_eq!(initial["retrieval"]["dense_desired"], n);
    assert_eq!(initial["retrieval"]["dense_published"], 0);
    let start = Instant::now();
    *gate.0.lock().unwrap() = true;
    gate.1.notify_all();
    let mut polls = Vec::new();
    let mut ready = false;
    while start.elapsed() < Duration::from_secs(120) {
        let sent_ms = start.elapsed().as_secs_f64()*1000.0;
        let t = Instant::now();
        let status = call_status();
        let elapsed_ms = t.elapsed().as_secs_f64()*1000.0;
        ready = status["retrieval"]["dense_state"] == "ready"
            && status["retrieval"]["semantic_pending"] == 0;
        polls.push(json!({"sent_ms":sent_ms,"duration_ms":elapsed_ms,"status":status,
            "fake_calls":provider.calls.load(Ordering::SeqCst),"fake_inputs":provider.inputs.load(Ordering::SeqCst)}));
        if ready { break; }
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
    let ready_ms = start.elapsed().as_secs_f64()*1000.0;
    let coverage = db.reads().semantic_coverage().unwrap();
    let errors = polls.iter().filter(|p| p["status"]["retrieval"]["index_state"] == "error").count();
    let total_status_ms: f64 = polls.iter().map(|p| p["duration_ms"].as_f64().unwrap()).sum();
    let mut steady = Vec::new();
    if ready {
        for _ in 0..128 {
            let t = Instant::now();
            let status = call_status();
            steady.push(t.elapsed().as_secs_f64()*1000.0);
            assert_eq!(status["retrieval"]["dense_published"], n);
            assert_eq!(status["retrieval"]["dense_desired"], n);
            assert_eq!(status["retrieval"]["generation"], json!(coverage.generation));
        }
    }
    let receipt = json!({"mode":mode,"files":n,"build_ms":build_ms,"poll_interval_ms":200,
        "timeout_seconds":120,"read_pool_size":1,"max_batch_items":16,"dimension":2,
        "ready":ready,"ready_ms":ready_ms,"polls":polls.len(),"latest_errors":errors,
        "status_total_ms":total_status_ms,"fake_calls":provider.calls.load(Ordering::SeqCst),
        "fake_inputs":provider.inputs.load(Ordering::SeqCst),"eligible":coverage.coverage.eligible,
        "published":coverage.coverage.published,"uncovered":coverage.coverage.uncovered,
        "steady_128_ms":steady,"initial":initial,"real_provider_calls":0,
        "level":"in-process actual production status + real SemanticRuntime/FakeProvider; no MCP RPC transport"});
    std::fs::write(out.join("polls.json"),serde_json::to_vec_pretty(&polls).unwrap()).unwrap();
    std::fs::write(out.join("receipt.json"),serde_json::to_vec_pretty(&receipt).unwrap()).unwrap();
    println!("{}",receipt);
    worker.close();
    index.close();
    assert!(ready, "original fixed 120s deadline not reached");
    assert_eq!(coverage.coverage.eligible as usize,n);
    assert_eq!(coverage.coverage.published as usize,n);
}
