import json,pathlib,gzip,hashlib
O=pathlib.Path(__file__).resolve().parent
read=lambda p:json.loads(p.read_text()) if p.exists() else json.load(gzip.open(str(p)+'.gz','rt'))
d=read(O/'paired-decision.json');sup=read(O/'supplemental-analysis.json');b=d['results']['baseline'];c=d['results']['candidate']
def fmt(v):return 'unknown / not_run' if v is None else f'{v:.6f}' if isinstance(v,float) else str(v)
def count(r,key):return r[key]['counts']['semantic_manifest'] if r.get(key) and r[key].get('counts') else None
def root(r):return r['resources']['root_and_server_observations']['product']
lines=['# localwidth4 新有限 100k 单次配对客观性能结果','',f"**硬 gate：baseline ready={b['readiness_pass']}；candidate ready={c['readiness_pass']}。自动 accept=False；生产集成=False。**",'',d['reason'],'','baseline → candidate 各正式一次；全部 release build 在前置和测量前完成。正确性另 session 独立 review，本报告只给客观结果，单次配对不作统计显著性声明。','','| 指标 | baseline | candidate |','| --- | ---: | ---: |']
metrics=[('fixed HEAD',b['source_sha'],c['source_sha']),('binary SHA256',b['binary_sha256'],c['binary_sha256']),('cold 秒',b['cold_seconds'],c['cold_seconds']),('300s 内 ready 秒',b['ready_seconds'],c['ready_seconds']),('cold+ready 秒',b['cold_plus_ready_seconds'],c['cold_plus_ready_seconds']),('原全部阶段结果',b['status'],c['status']),('resource guard',b.get('guard_stop') or 'none',c.get('guard_stop') or 'none'),('deadline 附近 manifest / 100000',count(b,'boundary'),count(c,'boundary')),('deadline 快照实际 elapsed 秒',b['boundary'].get('elapsed_drain_seconds') if b.get('boundary') else None,c['boundary'].get('elapsed_drain_seconds') if c.get('boundary') else None),('cleanup tail manifest',count(b,'cleanup_tail'),count(c,'cleanup_tail')),('cleanup tail elapsed 秒',b['cleanup_tail'].get('elapsed_drain_seconds') if b.get('cleanup_tail') else None,c['cleanup_tail'].get('elapsed_drain_seconds') if c.get('cleanup_tail') else None),('status observations/errors',f"{b['status_observations']}/{b['status_errors']}",f"{c['status_observations']}/{c['status_errors']}"),('status p50 / p95 ms',f"{b['status_latency_ms']['p50_ms']:.3f} / {b['status_latency_ms']['p95_ms']:.3f}",f"{c['status_latency_ms']['p50_ms']:.3f} / {c['status_latency_ms']['p95_ms']:.3f}"),('root sampled RSS max bytes',root(b)['sampled_max_rss_bytes'],root(c)['sampled_max_rss_bytes'])]
for k in ['cpu_user_seconds','cpu_system_seconds']:
 metrics.append(('last readable lifetime '+k,root(b)['last'][k],root(c)['last'][k]))
for k in ['write_bytes','rchar','read_bytes']:
 metrics.append(('last readable lifetime '+k,root(b)['last']['io'].get(k),root(c)['last']['io'].get(k)))
metrics.append(('原 postwrite log interval peak',sup['baseline']['http_observed_peak_active_intervals'],sup['candidate']['http_observed_peak_active_intervals']))
lines += [f'| {k} | {fmt(x)} | {fmt(y)} |' for k,x,y in metrics]
lines += ['', 'baseline actual production source=11f5b76273a16b520e6b6e01ad32a0a6743173fb；fixed HEAD=513a98c9a94b15ec77153df41af26fa3c8c0b5e8。crates、Cargo、lock、scripts 字节一致已核验。candidate=e3c04fed903c4d0e3c26b5d7cf0e055a6f7c5207。生产仅本地 attempt width2→4（受 claim budget 限制），provider gate/caps、claim16、fsync/cachelayout 保持原样。', '', '正式协议来自 PR124 c32a08a591e4fb1e9d457eee91b2703727b3d619 和所附 PR116 原协议：确定性 Rust source(i,value=0)，100000 文件，128dims，parse4，global4/perproject2，claim16，status gap .2s，release HTTP 后 ready300s，RPC300s，EOF15s，overall900s，fixture hold120s，memory12GiB/disk reserve4GiB。保留原后续 serial queries、4-way repeated/distinct concurrency、EOF、reopen。全部参数有原文件，不猜测。参考文件、实际 script、generator、lock、gate hash 见 protocol-source-hashes.json 和逐版 derivation patches。', '', '两版官方现成 direct Rust1.95.0 compiler，原 Cargo.lock，locked release --no-default-features --features semantic-http，semantic+semantic-http / opt3 / debug_assertions=false。独立 target，任务自有 Cargo cache 从已安装 registry 复制，不改官方 cache。全部构建结束后才开始任何产品前置与正式测量。独立 fresh synthetic repo/DB/cache、固定同一 loopback endpoint；未清 OS/page cache，baseline-first 顺序效应保留。', '', '前置是两版真实 production binary 的32文件受控 HTTP hold：两版 actual held=2、returned=0，128dims、batch16/caps4/2 与正式配置相同，status backfilling；新 candidate 自己的 real cache complete 到32条 manifest，然后 serial/concurrent queries、EOF、reopen 全部完成。前置不是独立验收。没有重跑先前被拒 runtime/EROFS case；没有复制被禁 localdiag / 实验2GB / 42file。', '', '两版 runtime status 未暴露 semantic provider effectivecaps：global/perproject runtime caps 为 unknown；execution counters 是 query pool，不能当 gate。受控 hold 无响应返回期间的实际 HTTP数可核验限流前置；正式 fixture 的 returned 在 response write 后记录，客户端可先释放 permit，因此 postwrite log interval peak>2 不证明 HTTP permit 违规。事件按 time_ns 排序分析，同时单列 append 顺序反转；actual HTTP batches 和 release/deadline/tail 分期见各版 extended-analysis.json，重叠窗口见 http-concurrency-windows.json。', '', 'deadline 附近 manifest 是只读事务的实际时间观察，不能冒称精确300.000000秒。cleanup tail 单列，期限外完成不算通过；失败 EOF cleanup 不是 post-ready 正常退出验收。ready 后原全部阶段只有实际通过 ready 才执行。旧 PR124 原300s 66867结果不改。', '', 'status errors/p50/p95 是已收到响应的观察。candidate 1次status无响应超时单列 event-timeline.json；原RPC300s等待不延长ready窗口。candidate最后HTTP活动为182.747秒，并由原memory guard终止，因此300秒快照是提前终止后的计数，不作完整300秒吞吐比较。两版post-ready阶段均not_run。SIGTERM关闭服务后root仍有RSS并可采样，持续到原RPC等待与EOF清理；不是继续HTTP/backfill的证明，post183秒CPU/IO采样差单列event-timeline.json。', '', 'RSS 是非原子20ms sampled值，不是 lifetime/PSS；完整 tree 若 children不可读就是unknown，observable sum 不替代完整tree。CPU/IO是最后可读累计值或phase采样端点差，未知不填0；read_bytes=0不表示没有读取。cgroup包括harness/build/cache，不当产品RSS。完成量不同，IO差异不能全部归因某项优化。']
for name,r in [('baseline',b),('candidate',c)]:
 lines += ['',f"{name}：not_run=`{json.dumps(r['not_run'])}`；post-ready normal EOF checked={r['post_ready_normal_exit_check']}；failure cleanup=`{json.dumps(r['cleanup_exit'])}`。",f"failures=`{json.dumps(r['failures'],ensure_ascii=False)}`。"]
lines += ['', '复核入口：paired-decision.json、supplemental-analysis.json、逐版 extended-analysis/resource-analysis/rpc-http-analysis/verification、preflight/sharedgate-preflight/summary、build receipts、压缩 RPC/HTTP/resource/source inputs。compare.py/supplement.py 只重放证据，不执行产品。SHA256SUMS 与 curated-manifest.json 覆盖精简本次证据；corpus/DB/cache/binaries/targets 不入 Git。生产、默认mode、4/2 caps、claim16、300s协议、fsync、cachelayout只读；无真实provider/heldout/GC/WALkill/crash/宽泛runtime。只checkpoint/push/draft PR，不merge/deploy；完成一对即停。']
(O/'README.md').write_text('\n'.join(lines)+'\n')
print('objective report generated')
