from pathlib import Path
import json,hashlib,datetime,collections
root=Path.cwd();source=root/'source';review=root/'review-runtime'
read=lambda p:json.loads(p.read_text())
def sha(p):
 h=hashlib.sha256()
 with p.open('rb') as f:
  for chunk in iter(lambda:f.read(1048576),b''):h.update(chunk)
 return h.hexdigest()
prefix='artifacts/benchmarks/p8-bfccb8494ba0'
def ref(relative):
 p=root/relative
 return {'path':prefix+'/'+relative,'sha256':sha(p),'bytes':p.stat().st_size}
tasks_doc=read(source/'docs/roadmap/code-index-v2/tasks.json');tasks={t['id']:t for t in tasks_doc['tasks']}
snapshot_sha=sha(source/'docs/roadmap/code-index-v2/tasks.json')
agg=read(review/'round4-p8-007-009-evidence-map.json')
identity=agg['identity']
assert identity['source_sha']=='a23bb72d3c954f385b99fe81ce9189885c208557'
assert sum(t['status']=='done' for t in tasks.values())==163
mixed=[]
for c,aid,jid,digest in [(1,11592751905,113631481248,'6cfceee02ed7fcd71039b9870e48457ddb3a7607935c7a5e798d549ee33123da'),(4,11591493782,113631481184,'727ab17068655b9ee5cd5677fb3f1a9fb4460c87266dfb0e6628d9a75678502c'),(8,11593165899,113631481186,'427906a25d21afae8085328c8fc92d6997763b1ad0f52247118052ec788118b8'),(16,11592154271,113631481232,'9ca7ff34acba74969feb840837d48ad89952efe06a9d02733c7c29d92efdf487')]:
 a='raw/'+str(aid)+'/extracted/';b=read(root/(a+'p8-build/build-receipt.json'));r=read(root/(a+'p8-runtime/report.json'));audit=read(review/('runtime-'+str(aid)+'-review-v2.json'))
 assert audit['review_status']=='raw_and_receipt_review_passed' and audit['errors']==[]
 assert b['source_before']==b['source_after'] and b['source_before']['source_commit']==identity['source_sha']
 mixed.append({'configured_concurrency':c,'actual_call_peak':audit['actual_concurrency']['maximum'],'read_build_overlap':audit['actual_concurrency']['read_build_overlap'],'run_id':37871838957,'job_id':jid,'artifact_id':aid,'artifact_url':'https://github.com/jyqj/codecortex/actions/runs/37871838957/artifacts/'+str(aid),'zip_sha256':digest,'artifact_path':prefix+'/raw/'+str(aid),'original_workload':{'files':1000,'operations':900,'build':300,'read':600,'successful':900,'actual_branch_switches':r['real_branch_switches'],'actual_catalog_compactions':r['observed_catalog_compactions']},'raw':ref(a+'p8-runtime/raw.jsonl'),'plan':ref(a+'p8-runtime/plan.json'),'report':ref(a+'p8-runtime/report.json'),'statistics':ref(a+'p8-runtime/statistics.json'),'statistics_replay':ref(a+'p8-runtime/statistics-replay.json'),'statistics_execution':ref(a+'p8-runtime/statistics-execution.json'),'runtime_seal':ref(a+'p8-runtime/seal.json'),'build_receipt':ref(a+'p8-build/build-receipt.json'),'build_seal':ref(a+'p8-build/seal.json'),'observer_before':b['observer_before'],'observer_after':b['observer_after'],'review':ref('review-runtime/runtime-'+str(aid)+'-review-v2.json')})
life_a='raw/11591607348/extracted/'
life_receipt=read(root/(life_a+'measurement/receipt.json'))
life_audit=read(review/'lifecycle-11591607348-review-v2.json')
assert life_audit['review_status']=='raw_and_receipt_review_passed' and life_audit['errors']==[]
lifecycle={'run_id':37871838975,'job_id':113631481484,'artifact_id':11591607348,'artifact_url':'https://github.com/jyqj/codecortex/actions/runs/37871838975/artifacts/11591607348','zip_sha256':'63aadf94879ea86782e9759828e853c1a030d70014fdc3fbdc127a18ca2eb055','artifact_path':prefix+'/raw/11591607348','raw_events':ref(life_a+'measurement/events.jsonl'),'replay_input':ref(life_a+'measurement/replay-input.json'),'report':ref(life_a+'measurement/report.json'),'replayed_report':ref(life_a+'measurement/report-replayed.json'),'repeat_replay_receipt':ref(life_a+'measurement/repeat-replay-receipt.json'),'receipt':ref(life_a+'measurement/receipt.json'),'product_build_receipt':ref(life_a+'product/build-receipt.json'),'evaluator_build_receipt':ref(life_a+'replay-build-receipt.json'),'observer_sha256':life_receipt['observer_sha256'],'review':ref('review-runtime/lifecycle-11591607348-review-v2.json')}
back_a='raw/11591821446/extracted/'
back_receipt=read(root/(back_a+'receipt.json'));back_audit=read(review/'backfill-11591821446-review.json')
assert back_audit['review_status']=='raw_and_receipt_review_passed' and back_audit['errors']==[]
backfill={'run_id':37871838957,'job_id':113631480994,'artifact_id':11591821446,'artifact_url':'https://github.com/jyqj/codecortex/actions/runs/37871838957/artifacts/11591821446','zip_sha256':'24fa1251fa006d23df2f801a7d5ba7eb420223c4a7dbd0cce7ab8fdcf6b36e15','artifact_path':prefix+'/raw/11591821446','receipt':ref(back_a+'receipt.json'),'seal':ref(back_a+'seal.json'),'execution_stdout':ref(back_a+'execution.stdout'),'execution_stderr':ref(back_a+'execution.stderr'),'observer_before':back_receipt['observer_before'],'observer_final':back_receipt['observer_final'],'review':ref('review-runtime/backfill-11591821446-review.json'),'original_population':{'seeds':[7,19,43],'phases':['quiet','held'],'concurrency':[1,4,8,16],'per_cell':32,'requests':768},'original_test':'real_slow_backfill_preserves_local_progress_and_records_every_request','scope':'same-process real CodeIndex workers with controlled fake provider; not a paid/live provider or independent stdio server performance experiment'}
common={'target_sha':identity['source_sha'],'status':'original_component_observations_reviewed_not_full_task_acceptance','review':'Independent pr_triage review of original fixed-a23 GitHub artifacts and their native execution/replay receipts; Mac replay of original Python validators and independent raw/stdio/statistical reconstruction. Original Linux ELF collectors and original Linux compiler paths were not reexecuted on Mac. No source, observer, original workload, validation gate, or task state was changed.','rollback_status':'Preserve every original raw file, failure/missing state and artifact; no release approval or candidate promotion is granted by this evidence.','source_binding':identity}
entries={}
def make(tid,summary,scope,paths,details,remaining):
 e=dict(common)
 e.update(summary=summary,scope=scope,artifact_paths=paths,original_hard_dependencies=[{'id':dep,'status_at_frozen_a23':tasks[dep]['status']} for dep in tasks[tid]['depends_on']],validation_ids=tasks[tid]['validations'],original_acceptance_unchanged=tasks[tid]['acceptance'],observations=details,remaining_acceptance=remaining)
 entries[tid]={'operation':'append_evidence_only_after_review','existing_task_status':'in_progress','proposed_task_status':'in_progress','keep_all_existing_evidence':True,'evidence_to_append':e}
make('P8-007','Four original default-product mixed profiles each retained and passed all 900 operations; configured C1/C4/C8/C16 had actual call peaks 1/4/7/12. Original controlled-backfill test passed all 768 requests across its 3 fixed seeds and C1/4/8/16. These are component observations, not closure of P8-007.','Original fixed offered schedules, all terminal denominators and queue/dispatch/service timing; actual C>1 read/build overlap; 15-table no-repair full-control parity; separately scoped original fake-provider worker contention.',[prefix+'/review-runtime/round4-p8-007-009-evidence-map.json']+[x['artifact_path'] for x in mixed]+[backfill['artifact_path']],{'mixed':mixed,'fake_backfill':backfill,'statistics_scope':'Each profile/concurrency and mutation stratum remains separate; original null CI endpoints and IID/descriptive limitations remain. Configured concurrency is never substituted for observed overlap. Default stdio mixed does not enable semantic backfill; the separate original worker test retains that scope.'},['Original hard dependency P8-006 remains in_progress at the frozen source.','Original V11/V20 and related regression closeout must be assessed against the complete fixed-source evidence set; no claim that this component set by itself satisfies every original task gate.'])
make('P8-008','Original lifecycle retained 30 cold, 400 process reopen, 400 warm uncached and 400 cache-hit samples: all 1230 succeeded. There was one separate unmeasured warmup, 431 owned product sessions and 1200 source-verified query witnesses; original native replay outputs were byte-identical.','Original full sample populations and their separate latency distributions/95% quantile intervals. OS page cache remains unknown and is not called cold disk. Cold N=30 retains unbounded p95/p99 CI endpoints; no new stable-tail or speedup claim.',[lifecycle['artifact_path'],prefix+'/review-runtime/lifecycle-11591607348-review-v2.json'],{'lifecycle':lifecycle,'sample_counts':life_audit['sample_counts'],'latency_layers':life_audit['latency_layers'],'original_native_replay_identical':True,'os_page_cache':life_receipt['os_page_cache']},['Original hard dependency P8-007 remains in_progress at the frozen source.','Original V20 and related regression closeout remain required; permitted unknown cache state is recorded rather than converted into an extra performance gate.'])
make('P8-009','Original lifecycle ledger retained 1261 stage snapshots with separate native client, server and owned-process-tree roles; physical storage, logical FTS and reported/estimated costs were independently checked without zero-filling unavailable values or double counting overlapping scopes.','Client current RSS from /proc/self, server native SELF RSS and owned process-tree snapshots keep their owners/methods. Runtime runner lifetime high-water is a separate profile. Physical SQLite objects are counted once; logical FTS remains contained within those bytes. Disabled-provider reported/estimated costs stay null.',[lifecycle['artifact_path'],prefix+'/review-runtime/lifecycle-11591607348-review-v2.json'],{'lifecycle':lifecycle,'memory_ledger':life_audit['memory_ledger'],'physical_components':life_audit['physical_components'],'disk_ledger':life_audit['disk_ledger'],'logical_fts_by_fixture':life_audit['logical_fts_by_fixture'],'provider_cost':life_audit['provider_cost'],'resource_interpretation':['1261 stage snapshots are not continuous process-tree peak coverage.','Client/server/tree maxima may be from different instants; server is already included in the tree; no total RSS sum.','30 closed cold fixtures and 90 physical identities are not one active-index footprint.','Unknown/unavailable values are allowed original outcomes and remain null; no added resource or performance gate.','Native server CPU ns and runner SELF seconds remain separate units; bracketing status overhead remains included.']},['Original hard dependency P8-008 remains in_progress at the frozen source.','Original V20 and related regression closeout remain required. Missing external/LSP/OCE/native-alternative observations are disclosed with their original null semantics, not treated as newly required paid-provider measurements.'])
make('P8-010','The original a23 one-hour soak is running; its workload step began at 2026-10-09T02:48:58Z. No original terminal workload verdict, complete soak artifact or raw acceptance result is available yet. No P8-010 completion claim is made.','Original 3601-operation / 1000-file / C4 / 1000ms schedule and required one-hour actual work. The original terminal outcome, RSS trend/coverage, actual Git/catalog work, cache/worker reuse and no-repair endpoint gates are all pending.',[prefix+'/review-runtime/round4-p8-007-009-evidence-map.json'],{'runtime_run_id':37871838957,'soak_job_id':113631481157,'job_url':'https://github.com/jyqj/codecortex/actions/runs/37871838957/job/113631481157','observed_job_status':'in_progress','observed_step':'One-hour actual stdio session with Git switches and catalog churn','workload_step_started_at':'2026-10-09T02:48:58Z','last_status_checked_at':'2026-10-09T03:25:54Z','terminal_conclusion':None,'artifact_id':None,'raw_acceptance':None,'original_plan':{'files':1000,'concurrency':4,'operations':3601,'builds':1201,'compound_reads':2400,'requests_per_read':['before_status','symbol','hybrid','after_status'],'interval_ms':1000,'minimum_actual_work_ns':3600000000000},'prepared_readonly_review_programs':[ref('review-runtime/runtime-independent-review-v2.py'),ref('review-runtime/soak-stdio-binding-review.py')]},['Original hard dependency P8-009 remains in_progress at the frozen source.','Wait for the original terminal job; preserve native failure, canceled and missing outcomes if any occur.','Obtain the original complete artifact and verify GitHub ZIP digest, source/observer/build receipts, every raw/seal entry, original statistics double replay and original process cleanup.','Apply the unchanged original workload/RSS coverage and trend/cache four-quarter/no-repair full-15-table gates; successful seal verification alone is insufficient.','Original V07/V17/V20 and related regression closeout remain required.'])
entries['P8-010']['evidence_to_append']['status']='original_execution_pending_no_acceptance_verdict'
doc={'schema_version':1,'document_kind':'review_only_candidate_task_evidence_append_entries','generated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'frozen_source':identity,'frozen_tasks_path':'docs/roadmap/code-index-v2/tasks.json','frozen_tasks_sha256':snapshot_sha,'baseline':{'total':192,'done':163,'remaining':29,'new_closures':0},'instructions':'Review-only staging. Do not replace existing evidence, change any status, weaken original dependencies, or silently rewrite the pending soak entry. After a genuine original terminal result, retain this pending snapshot and append a separately dated terminal assessment.','proposals':entries}
json_path=review/'p8-007-010-evidence-append-draft.json';json_path.write_text(json.dumps(doc,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
lines=['# P8-007～010 原任务 evidence 追加草案','','本文件仅供审查；对应 JSON 未写入 tasks.json，四项状态都保持 in_progress，基线 163 done / 29 剩余。已有 evidence 应完整保留，不能由本草案覆盖。','','source: '+identity['source_sha'],'','| 任务 | 可追加的原观测范围 | 仍须保留的原硬依赖 | 终态/范围 |','|---|---|---|---|','| P8-007 | C1/C4/C8/C16 四档 mixed 各 900 次，加独立原 fake-backfill 768 次 | P8-006 | 原 component 已审，不能单凭组件通过关闭原任务 |','| P8-008 | 30 cold + 400 reopen + 400 warm uncached + 400 cache-hit，原双 replay | P8-007 | 原分层已审；OS page cache unknown、cold CI 的 null 上界保留 |','| P8-009 | 1261 原 client/server/tree 阶段快照，物理 SQLite/逻辑 FTS/费用账本 | P8-008 | 单位/归属已审；合法 unavailable 不新增性能门 |','| P8-010 | 原 3601 次/1000 files/1 小时 soak 的真实执行身份与待验收项 | P8-009 | 仍在原 workload，没有终态、完整 artifact 或 raw 通过结论 |','','JSON 中每项提供现有 evidence 常用字段 target_sha、status、artifact_paths、scope、review、rollback_status、summary，并附原 source/observer/build/raw/statistics/receipt 的具体路径和 SHA256。P8-007 单独保存各 C 的实际峰值 1/4/7/12，不用配置值冒充实测并发；P8-008/009 共用同一原件但保留不同验收含义。','','P8-010 当前 pending 记录必须保留为时间点事实。原 soak 终态后应追加独立终态评估，附完整原 artifact、原 RSS/缓存/四季度/15 表门结果；不得把本 pending 条目无说明改成已通过。原 V11/V20、V07/V17/V20 以及相关旧功能回归与任务依赖仍由完整集成审查闭环。','','候选条目：[p8-007-010-evidence-append-draft.json](p8-007-010-evidence-append-draft.json)；没有改 tasks.json。']
md=review/'p8-007-010-evidence-append-draft.md';md.write_text('\n'.join(lines)+'\n')
assert sha(source/'docs/roadmap/code-index-v2/tasks.json')==snapshot_sha
print(json.dumps({'review_only':True,'source':identity['source_sha'],'tasks_unchanged':True,'baseline':doc['baseline'],'proposals':list(entries),'json':str(json_path),'json_sha256':sha(json_path),'markdown':str(md),'markdown_sha256':sha(md)},ensure_ascii=False))
