//! Task-text activation signal.
//!
//! Owns the framework -> activation-literal table consumed by
//! `compute_active_frameworks` in the module root: a framework gains a medium
//! activation tier when at least two of its literals appear in the task text.

// ---------------------------------------------------------------------------
// Activation literals table (for compute_active_frameworks task text matching)
// ---------------------------------------------------------------------------

pub(super) fn activation_literals_table() -> &'static [(&'static str, &'static [&'static str])] {
    &[
        (
            "express",
            &[
                "express",
                "router",
                "middleware",
                "req",
                "res",
                "app.get",
                "app.post",
            ],
        ),
        (
            "fastify",
            &["fastify", "reply", "request.body", "server.listen"],
        ),
        (
            "react",
            &[
                "useState",
                "useEffect",
                "component",
                "jsx",
                "props",
                "render",
            ],
        ),
        (
            "nextjs",
            &[
                "nextjs",
                "next",
                "getServerSideProps",
                "getStaticProps",
                "NextRequest",
                "NextResponse",
                "app router",
            ],
        ),
        (
            "nestjs",
            &[
                "nestjs",
                "@Controller",
                "@Injectable",
                "@Module",
                "@Get",
                "@Post",
                "dependency injection",
            ],
        ),
        (
            "fastapi",
            &[
                "fastapi",
                "uvicorn",
                "Depends",
                "HTTPException",
                "pydantic",
                "BaseModel",
            ],
        ),
        (
            "django",
            &[
                "django",
                "urlpatterns",
                "HttpResponse",
                "models.Model",
                "admin.site",
            ],
        ),
        (
            "spring",
            &[
                "spring",
                "SpringBootApplication",
                "RestController",
                "RequestMapping",
                "GetMapping",
                "PostMapping",
                "Autowired",
            ],
        ),
        ("chi", &["chi", "go-chi", "chi.NewRouter", "chi.Router"]),
        (
            "gorilla",
            &["gorilla", "mux.NewRouter", "mux.Router", "gorilla/mux"],
        ),
        (
            "gin",
            &[
                "gin",
                "gin.Default",
                "gin.New",
                "gin.Context",
                "r.GET",
                "r.POST",
            ],
        ),
        (
            "echo",
            &["echo", "echo.New", "echo.Context", "e.GET", "e.POST"],
        ),
        (
            "axum",
            &[
                "axum",
                "Router::new",
                ".route(",
                "axum::extract",
                "axum::response",
            ],
        ),
        (
            "actix",
            &[
                "actix",
                "actix-web",
                "HttpServer",
                "web::get",
                "web::post",
                "web::resource",
            ],
        ),
        (
            "rocket",
            &[
                "rocket",
                "#[get",
                "#[post",
                "rocket::launch",
                "rocket::routes",
            ],
        ),
        (
            "laravel",
            &[
                "laravel",
                "Eloquent",
                "Illuminate",
                "artisan",
                "Route::get",
                "Route::post",
            ],
        ),
        (
            "rails",
            &[
                "rails",
                "ActiveRecord",
                "ActionController",
                "routes.rb",
                "resources",
            ],
        ),
        (
            "aspnet",
            &[
                "asp.net",
                "aspnet",
                "ApiController",
                "HttpGet",
                "HttpPost",
                "IActionResult",
            ],
        ),
        (
            "sveltekit",
            &[
                "sveltekit",
                "svelte",
                "+page.svelte",
                "+server",
                "load function",
            ],
        ),
        (
            "nuxt",
            &[
                "nuxt",
                "nuxt3",
                "useFetch",
                "defineNuxtConfig",
                "useAsyncData",
            ],
        ),
        (
            "remix",
            &["remix", "@remix-run", "loader", "action", "useLoaderData"],
        ),
        (
            "vue_router",
            &[
                "vue-router",
                "router",
                "useRoute",
                "useRouter",
                "createRouter",
            ],
        ),
        (
            "hono",
            &["hono", "Hono", "app.get", "app.post", "c.json", "c.text"],
        ),
    ]
}
