"""Run the unchanged v14 proof in its fixed, byte-checked historical context.

Only immutable Git blobs are cached. Current protection files, snapshot bytes
and every prior approval function are checked again for each proof. No corpus
discovery, heldout body, model, checkout or replacement approval is involved.
"""

from functools import lru_cache
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
HISTORICAL_HEAD = "7354db236c9d9850a75f31672697ae9eab44565e"
VALIDATION_ROOTS = ("scripts", ".github/workflows", "tests/source_integrity")
REGISTRIES = (
    "scripts/current-source-registry-v1.json",
    "scripts/current-source-registry-v2.json",
    "scripts/current-source-registry-v3.json",
    "scripts/reviewed-source-registry.json",
    "scripts/reviewed-source-p7-v9.json",
    "scripts/reviewed-source-joint22-v10.json",
)
EXPLICIT_RECORDS = (
    "docs/checkpoints/2026-10-03-packing-integration/original-tests/qname_db_independent_review.rs",
    "artifacts/checkpoints/bounded-integration-20261004/test-only-lint-fix/engine_lane_tests.rs.original",
    "artifacts/checkpoints/python-resource-integration-20261004/python_identity_independent.rs.original",
    "artifacts/checkpoints/p8-next-ten-20261008/source-review.json",
    "artifacts/checkpoints/p8-next-ten-20261008/ci/worker-source-review.json",
    "artifacts/checkpoints/p8-next-ten-20261008/release/main-merge-source-review.json",
    "artifacts/checkpoints/p7-closeout-20261008/independent-source-review.json",
    "artifacts/checkpoints/p8-corpus-external-holdout-20261008/round5/independent-source-review.json",
)
MAX_BLOB = 64 * 1024 * 1024
MAX_TOTAL = 256 * 1024 * 1024
MAX_FILES = 2000


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def verify_pin():
    require(not sys.flags.optimize, "historical context requires Python without -O")
    require(isinstance(HISTORICAL_HEAD, str) and re.fullmatch(r"[0-9a-f]{40}", HISTORICAL_HEAD),
            "historical context requires an immutable full commit SHA")


def relative(path):
    require(isinstance(path, str) and path and not path.startswith("/") and "\\" not in path
            and all(part not in ("", ".", "..", ".git") for part in path.split("/"))
            and not any(ord(c) < 32 or ord(c) == 127 for c in path), "unsafe historical path")
    require(path in EXPLICIT_RECORDS or not re.search(r"hold[-_]?out|held[-_]?out", path, re.I), "protected body path")
    return path


def git(*arguments):
    command = ["git", "--no-pager", "-c", "core.fsmonitor=false", "-C", str(ROOT), *arguments]
    result = subprocess.run(command, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                            stderr=subprocess.DEVNULL, timeout=60,
                            env={**os.environ, "GIT_TERMINAL_PROMPT": "0", "GIT_NO_LAZY_FETCH": "1",
                                 "GIT_OPTIONAL_LOCKS": "0"})
    require(result.returncode == 0 and len(result.stdout) <= MAX_BLOB, "historical Git input unavailable")
    return result.stdout


def ensure_history():
    verify_pin()
    try:
        git("cat-file", "-e", HISTORICAL_HEAD + "^{commit}")
    except AssertionError:
        # CI may be a shallow checkout. Fetch only this immutable object; never
        # select a branch, change a worktree, or discover other corpus material.
        git("fetch", "--no-tags", "origin", HISTORICAL_HEAD)
        git("cat-file", "-e", HISTORICAL_HEAD + "^{commit}")


@lru_cache(None)
def _blob(ref, path):
    relative(path)
    entry = git("ls-tree", "-z", ref, "--", ":(literal)" + path).split(b"\0")
    require(len(entry) == 2 and entry[-1] == b"", "missing historical file")
    metadata, actual = entry[0].split(b"\t", 1)
    require(metadata.split()[:2] in ([b"100644", b"blob"], [b"100755", b"blob"])
            and actual.decode() == path, "nonregular historical Git input")
    return git("show", ref + ":" + path)


def fixed_blob(path):
    verify_pin()
    return _blob(HISTORICAL_HEAD, relative(path))


@lru_cache(None)
def _catalogue(ref):
    names = set()
    for row in git("ls-tree", "-r", "-z", ref, "--", *VALIDATION_ROOTS).split(b"\0"):
        if not row:
            continue
        metadata, path = row.decode().split("\t", 1)
        mode, kind, _oid = metadata.split()
        require(kind == "blob" and mode in {"100644", "100755"}, "nonregular historical validation input")
        require(not ("__pycache__" in Path(path).parts and path.endswith(".pyc")),
                "generated bytecode unexpectedly tracked in history")
        names.add(relative(path))
    records = set(EXPLICIT_RECORDS)
    for path in REGISTRIES:
        registry = json.loads(_blob(ref, path))
        records.update(registry.get("records", {}))
        records.update(row["review_path"] for row in registry.get("deltas", {}).values())
    names.update(relative(path) for path in records)
    require(0 < len(names) <= MAX_FILES, "historical input count exceeds bound")
    blobs = {path: _blob(ref, path) for path in sorted(names)}
    require(sum(map(len, blobs.values())) <= MAX_TOTAL, "historical input byte budget")
    protected = records | {path for path in names if (
        path.startswith("tests/source_integrity/")
        or path.startswith("scripts/source_snapshots/")
        or (path.startswith("scripts/") and Path(path).name.startswith(("verify_", "current-source-", "reviewed-source-", "v14_historical_")))
        or path == "scripts/p0_historical_corpus.py")}
    return blobs, frozenset(protected)


def catalogue():
    ensure_history()
    blobs, protected = _catalogue(HISTORICAL_HEAD)
    return dict(blobs), protected


def checked_file(root, path):
    """Reject a symlink at the file, any relative parent, or the root itself."""
    root = Path(root).absolute()
    require(root.is_dir() and not root.is_symlink(), "historical protection root is not a real directory")
    target = root
    for part in Path(relative(path)).parts:
        target /= part
        try:
            mode = target.lstat().st_mode
        except FileNotFoundError:
            raise AssertionError("historical protection input missing: " + path) from None
        require(not stat.S_ISLNK(mode), "historical protection symlink: " + path)
    require(stat.S_ISREG(mode), "nonregular historical protection input: " + path)
    return target


def verify_current_history(root=ROOT):
    blobs, protected = catalogue()
    for path in sorted(protected):
        require(checked_file(root, path).read_bytes() == blobs[path],
                "current historical protection changed: " + path)
    return {path: hashlib.sha256(blobs[path]).hexdigest() for path in sorted(protected)}


class HistoricalContext:
    def __init__(self, current_root=ROOT):
        self.current_root = Path(current_root)
        verify_current_history(self.current_root)
        self._temporary = tempfile.TemporaryDirectory(prefix="codecortex-v14-history-")
        self.root = Path(self._temporary.name)
        blobs, _ = catalogue()
        for path, raw in blobs.items():
            target = self.root / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(raw)
            target.chmod(0o444)
        self.verify()

    def verify(self):
        blobs, _ = catalogue()
        disk = {path.relative_to(self.root).as_posix() for path in self.root.rglob("*")
                if path.is_file() or path.is_symlink()}
        require(disk == set(blobs), "historical context inventory differs")
        for path, raw in blobs.items():
            require(checked_file(self.root, path).read_bytes() == raw,
                    "historical context bytes changed: " + path)

    def before(self):
        verify_current_history(self.current_root)
        self.verify()

    def after(self):
        self.verify()
        verify_current_history(self.current_root)

    def approved_union(self, previous, registry=None):
        self.before()
        if registry is None:
            registry = previous.load_registry(self.root / "scripts/reviewed-source-registry-v14.json")
        result = previous.approved_union(registry, root=self.root)
        previous.verify_ci(root=self.root)
        self.after()
        return result

    def close(self):
        self._temporary.cleanup()

    def __enter__(self):
        return self

    def __exit__(self, *_exc):
        self.close()


def approved_union(previous, registry=None, root=ROOT):
    with HistoricalContext(root) as context:
        return context.approved_union(previous, registry)
