#!/usr/bin/env python3
"""Verify the existing approval chains and an independently reviewed P7 delta.

The new record admits fixed implementation and validation inputs. It neither
relabels historical executions nor grants task, quality or release approval.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

import verify_reviewed_source_v12 as previous

ROOT = Path(__file__).resolve().parents[1]
VERSION = "p7-closeout-source-20261008-v13"
BASE = "47d1939e43455ecd72ccc73e80825d971e3f33e7"
PRODUCT = "e7b165b1b121a9b477fe98635000437b8c6e6f24"
REVIEW = "706198f96a6da352916804c43f31b59f3805cba1"
REVIEW_PATH = "artifacts/checkpoints/p7-closeout-20261008/independent-source-review.json"
REGISTRY = ROOT / "scripts/reviewed-source-registry-v13.json"
REGISTRY_SHA256 = "f95cda953f169115b4ece98fd9431bcf43cb358e882bb6e3748df3054472262e"
CI_SNAPSHOT = "scripts/source_snapshots/v12_ci"
FROZEN = (
    "scripts/verify_reviewed_source_v12.py",
    "scripts/reviewed-source-registry-v12.json",
    "tests/source_integrity/test_reviewed_source_v12.py",
)
VALIDATION_ROOTS = ("scripts", ".github/workflows", "tests/source_integrity")
# The selected guard and its registry are the new trust root. Their fixed
# references are installed after the reviewed product commit. The current CI
# selector is separately constrained by expected_ci(), which runs the old proof.
VALIDATION_EXCLUSIONS = frozenset({
    "scripts/verify_reviewed_source_v13.py",
    "scripts/reviewed-source-registry-v13.json",
    ".github/workflows/ci.yml",
})
git = previous.git
require = previous.require


def identities():
    return dict(schema_version=8, source_version=VERSION,
                previous_source_version=previous.VERSION, base_source=BASE,
                product_source=PRODUCT, review_source=REVIEW,
                scope="independently_reviewed_source_and_validation_inputs",
                runtime_and_quality_claims="require_separate_execution_evidence")


def verify_pins():
    require(all(isinstance(pin, str) and re.fullmatch(r"[0-9a-f]{40}", pin)
                for pin in (BASE, PRODUCT, REVIEW)),
            "v13 pins must be immutable full commit SHAs")


def check_identity(registry):
    verify_pins()
    for key, value in identities().items():
        require(registry.get(key) == value, "wrong v13 identity: " + key)


def load_registry(path=REGISTRY):
    raw = path.read_bytes()
    require(hashlib.sha256(raw).hexdigest() == REGISTRY_SHA256,
            "stale or altered v13 registry")
    registry = json.loads(raw)
    check_identity(registry)
    return registry


def unchanged_file(root, path, raw, label):
    target = root / path
    require(not target.is_symlink() and target.is_file() and target.read_bytes() == raw,
            label + ": " + path)


def validation_path(path):
    # CPython's generated bytecode is not a source input. A new Python/YAML or
    # other regular input is still detected, including inside __pycache__.
    generated = "__pycache__" in Path(path).parts and path.endswith(".pyc")
    return path not in VALIDATION_EXCLUSIONS and not generated


def validation_inventory(ref):
    rows = git.git("ls-tree", "-r", "-z", ref, "--", *VALIDATION_ROOTS)
    result = {}
    for row in rows.split(b"\0"):
        if not row:
            continue
        metadata, path = row.decode().split("\t", 1)
        mode, kind, _oid = metadata.split()
        if validation_path(path):
            require(kind == "blob" and mode in {"100644", "100755"},
                    "unsupported validation input mode: " + path)
            result[path] = git.sha(git.blob(ref, path))
    return result


def verify_validation_inventory(root, expected):
    disk = {path.relative_to(root).as_posix()
            for directory in VALIDATION_ROOTS for path in (root / directory).rglob("*")
            if (path.is_file() or path.is_symlink())
            and validation_path(path.relative_to(root).as_posix())}
    require(disk == set(expected), "v13 validation disk inventory differs")
    # The byte and symlink check runs separately for every reviewed input below.


def verify_snapshots(root=ROOT):
    verify_pins()
    git.ensure_refs([BASE, PRODUCT, REVIEW])
    for path in FROZEN:
        unchanged_file(root, path, git.blob(BASE, path), "v12 approval snapshot changed")
    for path in (".github/workflows/ci.yml", ".github/workflows/p7-engineering.yml"):
        unchanged_file(root, CI_SNAPSHOT + "/" + path, git.blob(BASE, path),
                       "v12 CI snapshot changed")
    # Execute the old CI proof in its exact historical workflow snapshot.
    previous.verify_ci(root / CI_SNAPSHOT)


def reconstruct(registry, inherited, root=ROOT):
    check_identity(registry)
    require(set(inherited) == git.inputs(BASE)
            and all(raw == git.blob(BASE, path) for path, raw in inherited.items()),
            "v13 base is not the proven inherited source")
    source_inputs = git.inputs(PRODUCT)
    changes = previous.changed_paths(BASE, PRODUCT)
    delta = registry.get("delta", {})
    require(isinstance(delta, dict) and changes == set(delta) and bool(changes),
            "v13 reviewed source delta inventory differs")
    # Deletions are deliberately not part of this fixed implementation review.
    require(set(inherited) <= source_inputs, "v13 source unexpectedly removes an inherited input")
    raw_review = git.blob(REVIEW, REVIEW_PATH)
    require(git.sha(raw_review) == registry.get("review_sha256"), "v13 review digest differs")
    unchanged_file(root, REVIEW_PATH, raw_review, "v13 fixed independent review changed")
    review = json.loads(raw_review)
    require(review.get("source") == PRODUCT and review.get("base") == BASE
            and review.get("verdict") == "accepted_scoped"
            and review.get("independent_reviewers")
            and review.get("unresolved_blockers") == []
            and set(review.get("paths", {})) == changes,
            "v13 review does not accept the exact source delta")
    result = dict(inherited)
    for path in sorted(changes):
        before = inherited.get(path)
        after = git.blob(PRODUCT, path)
        expected = {"before_sha256": None if before is None else git.sha(before),
                    "sha256": git.sha(after)}
        require(delta[path] == expected, "v13 before/after digest differs: " + path)
        require(review["paths"][path] == expected,
                "v13 independent source review differs: " + path)
        result[path] = after
    require(set(result) == source_inputs
            and all(raw == git.blob(PRODUCT, path) for path, raw in result.items()),
            "v13 complete source inventory or bytes differ")
    require({path: git.sha(raw) for path, raw in result.items()}
            == registry.get("complete_inputs"), "v13 complete manifest differs")
    extra = registry.get("validation_inputs")
    require(isinstance(extra, dict) and extra
            and review.get("validation_inputs") == extra,
            "v13 validation review inventory differs")
    require(extra == validation_inventory(PRODUCT), "v13 complete validation manifest differs")
    verify_validation_inventory(root, extra)
    for path, digest in extra.items():
        require(isinstance(path, str) and path.startswith(tuple(x + "/" for x in VALIDATION_ROOTS))
                and ".." not in Path(path).parts, "invalid v13 validation input")
        raw = git.blob(PRODUCT, path)
        require(git.sha(raw) == digest, "v13 validation source digest differs: " + path)
        unchanged_file(root, path, raw, "v13 reviewed validation input changed")
    return result


def approved_union(registry, root=ROOT):
    verify_snapshots(root)
    inherited = previous.approved_union(previous.load_registry(), root=root)
    return reconstruct(registry, inherited, root=root)


def expected_ci():
    original = previous.expected_ci()
    old = "verify_reviewed_source_v12.py --source-version " + previous.VERSION
    new = "verify_reviewed_source_v13.py --source-version " + VERSION
    require(original.count(old) == 1, "v12 CI selector differs")
    return original.replace(old, new)


def verify_ci(root=ROOT):
    target = root / ".github/workflows/ci.yml"
    require(not target.is_symlink() and target.is_file()
            and target.read_text() == expected_ci(),
            "CI differs beyond the explicit v13 selector")
    unchanged_file(root, ".github/workflows/p7-engineering.yml",
                   git.blob(BASE, ".github/workflows/p7-engineering.yml"),
                   "P7 engineering workflow changed")


def main():
    if sys.flags.optimize:
        raise SystemExit("source verification requires Python without -O")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-version", required=True, choices=[VERSION])
    parser.parse_args()
    expected = approved_union(load_registry())
    tracked = git.git("ls-files", "--", "crates", "Cargo.toml", "Cargo.lock")
    git.verify_tree(ROOT, expected, tracked.decode().splitlines())
    validation_tracked = git.git("ls-files", "--", *VALIDATION_ROOTS).decode().splitlines()
    require({path for path in validation_tracked if validation_path(path)}
            == set(validation_inventory(PRODUCT)), "v13 tracked validation inventory differs")
    verify_ci()
    print(json.dumps(dict(identities(), status="passed", complete_inputs=len(expected),
                          executed_previous_proof=previous.VERSION)))


if __name__ == "__main__":
    main()
