#!/usr/bin/env python3
"""Verify the existing approval chains and an independently reviewed P8 engineering delta.

The new record admits fixed implementation and validation inputs. It neither
relabels historical executions nor grants task, quality or release approval.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

import verify_reviewed_source_v14 as previous
import v15_historical_context as history

ROOT = Path(__file__).resolve().parents[1]
VERSION = "p8-completion-source-20261009-v15"
BASE = "7354db236c9d9850a75f31672697ae9eab44565e"
PRODUCT = "362a8216537dd1df614077abc6b6e2f98ef8a054"
REVIEW = "32f86004f823d21a3b2412f1e652bb3d581c9315"
REVIEW_PATH = "artifacts/checkpoints/p8-completion-20261009/independent-source-review.json"
REGISTRY = ROOT / "scripts/reviewed-source-registry-v15.json"
REGISTRY_SHA256 = "f3c63149ca07907628e1174616fe3f0fddff3b1c003f49933127c635aa4b0e75"
FROZEN = (
    "scripts/verify_reviewed_source_v14.py",
    "scripts/reviewed-source-registry-v14.json",
    "tests/source_integrity/test_reviewed_source_v14.py",
    "scripts/v14_historical_context.py",
    "tests/source_integrity/v14_historical_test_adapter.py",
    "tests/source_integrity/test_v14_historical_context.py",
)
VALIDATION_ROOTS = ("scripts", ".github/workflows", "tests/source_integrity")
# The selected guard and its registry are the new trust root. Their fixed
# references are installed after the reviewed product commit. The current CI
# selector is separately constrained by expected_ci(), which runs the old proof.
VALIDATION_EXCLUSIONS = frozenset({
    "scripts/verify_reviewed_source_v15.py",
    "scripts/reviewed-source-registry-v15.json",
    ".github/workflows/ci.yml",
})
git = previous.git
require = previous.require


def identities():
    return dict(schema_version=10, source_version=VERSION,
                previous_source_version=previous.VERSION, base_source=BASE,
                product_source=PRODUCT, review_source=REVIEW,
                scope="independently_reviewed_source_and_validation_inputs",
                runtime_and_quality_claims="require_separate_execution_evidence")


def verify_pins():
    require(all(isinstance(pin, str) and re.fullmatch(r"[0-9a-f]{40}", pin)
                for pin in (BASE, PRODUCT, REVIEW)),
            "v15 pins must be immutable full commit SHAs")
    require(isinstance(REGISTRY_SHA256, str)
            and re.fullmatch(r"[0-9a-f]{64}", REGISTRY_SHA256),
            "v15 registry digest must be a fixed SHA-256")


def check_identity(registry):
    verify_pins()
    for key, value in identities().items():
        require(registry.get(key) == value, "wrong v15 identity: " + key)


def load_registry(path=REGISTRY):
    verify_pins()
    raw = path.read_bytes()
    require(hashlib.sha256(raw).hexdigest() == REGISTRY_SHA256,
            "stale or altered v15 registry")
    registry = json.loads(raw)
    check_identity(registry)
    return registry


def unchanged_file(root, path, raw, label):
    root = Path(root)
    require(root.is_dir() and not root.is_symlink(), label + ": invalid root")
    relative = Path(path)
    require(not relative.is_absolute() and ".." not in relative.parts,
            label + ": invalid path")
    target = root
    for part in relative.parts:
        target /= part
        require(not target.is_symlink(), label + ": symlink input: " + path)
    require(target.is_file() and target.read_bytes() == raw, label + ": " + path)


def validation_path(path):
    # CPython's generated bytecode is not a source input. A new Python/YAML or
    # other regular input is still detected, including inside __pycache__.
    generated = "__pycache__" in Path(path).parts and path.endswith(".pyc")
    return path not in VALIDATION_EXCLUSIONS and not generated


def validation_inventory(ref):
    rows = git.git("ls-tree", "-r", "-z", ref, "--", *VALIDATION_ROOTS)
    result = {}
    for row in rows.split(b"\0"):
        if not row:
            continue
        metadata, path = row.decode().split("\t", 1)
        mode, kind, _oid = metadata.split()
        if validation_path(path):
            require(kind == "blob" and mode in {"100644", "100755"},
                    "unsupported validation input mode: " + path)
            result[path] = git.sha(git.blob(ref, path))
    return result


def verify_validation_inventory(root, expected):
    disk = {path.relative_to(root).as_posix()
            for directory in VALIDATION_ROOTS for path in (root / directory).rglob("*")
            if (path.is_file() or path.is_symlink())
            and validation_path(path.relative_to(root).as_posix())}
    require(disk == set(expected), "v15 validation disk inventory differs")
    # The byte and symlink check runs separately for every reviewed input below.


def verify_validation_inputs(root, expected):
    """Check the complete current validation domain before the old proof runs."""
    verify_validation_inventory(root, expected)
    for path, digest in expected.items():
        require(isinstance(path, str) and path.startswith(tuple(x + "/" for x in VALIDATION_ROOTS))
                and ".." not in Path(path).parts, "invalid v15 validation input")
        raw = git.blob(PRODUCT, path)
        require(git.sha(raw) == digest, "v15 validation source digest differs: " + path)
        unchanged_file(root, path, raw, "v15 reviewed validation input changed")


def verify_snapshots(root=ROOT):
    verify_pins()
    require(BASE == history.HISTORICAL_HEAD, "v15 historical base differs")
    git.ensure_refs([BASE, PRODUCT, REVIEW])
    history.verify_current_history(root)
    for path in FROZEN:
        unchanged_file(root, path, git.blob(BASE, path), "v14 approval snapshot changed")


def reconstruct(registry, inherited, root=ROOT):
    check_identity(registry)
    require(set(inherited) == git.inputs(BASE)
            and all(raw == git.blob(BASE, path) for path, raw in inherited.items()),
            "v15 base is not the proven inherited source")
    source_inputs = git.inputs(PRODUCT)
    changes = set(git.git("diff", "--name-only", BASE, PRODUCT, "--",
                          "crates", "Cargo.toml", "Cargo.lock").decode().splitlines())
    delta = registry.get("delta", {})
    require(isinstance(delta, dict) and changes == set(delta) and bool(changes),
            "v15 reviewed source delta inventory differs")
    # Deletions are deliberately not part of this fixed implementation review.
    require(set(inherited) <= source_inputs, "v15 source unexpectedly removes an inherited input")
    raw_review = git.blob(REVIEW, REVIEW_PATH)
    require(git.sha(raw_review) == registry.get("review_sha256"), "v15 review digest differs")
    unchanged_file(root, REVIEW_PATH, raw_review, "v15 fixed independent review changed")
    review = json.loads(raw_review)
    require(review.get("source") == PRODUCT and review.get("base") == BASE
            and review.get("verdict") == "accepted_scoped"
            and review.get("scope") == identities()["scope"]
            and isinstance(review.get("independent_reviewers"), list)
            and bool(review["independent_reviewers"])
            and all(isinstance(name, str) and name.strip()
                    for name in review["independent_reviewers"])
            and review.get("unresolved_blockers") == []
            and set(review.get("paths", {})) == changes,
            "v15 review does not accept the exact source delta")
    result = dict(inherited)
    for path in sorted(changes):
        before = inherited.get(path)
        after = git.blob(PRODUCT, path)
        expected = {"before_sha256": None if before is None else git.sha(before),
                    "sha256": git.sha(after)}
        require(delta[path] == expected, "v15 before/after digest differs: " + path)
        require(review["paths"][path] == expected,
                "v15 independent source review differs: " + path)
        result[path] = after
    require(set(result) == source_inputs
            and all(raw == git.blob(PRODUCT, path) for path, raw in result.items()),
            "v15 complete source inventory or bytes differ")
    complete = {path: git.sha(raw) for path, raw in result.items()}
    require(complete == registry.get("complete_inputs"), "v15 complete manifest differs")
    require(review.get("complete_inputs") == complete,
            "v15 independent review complete manifest differs")
    extra = registry.get("validation_inputs")
    require(isinstance(extra, dict) and extra
            and review.get("validation_inputs") == extra,
            "v15 validation review inventory differs")
    require(extra == validation_inventory(PRODUCT), "v15 complete validation manifest differs")
    verify_validation_inputs(root, extra)
    return result


def approved_union(registry, root=ROOT):
    check_identity(registry)
    git.ensure_refs([BASE, PRODUCT, REVIEW])
    # The new helper, tests and adapter are reviewed inputs, not exclusions.
    # Reject their current bytes before any historical-context proof uses them.
    verify_validation_inputs(root, validation_inventory(PRODUCT))
    verify_snapshots(root)
    inherited = history.approved_union(previous, root=root)
    return reconstruct(registry, inherited, root=root)


def expected_ci():
    original = previous.expected_ci()
    old = "verify_reviewed_source_v14.py --source-version " + previous.VERSION
    new = "verify_reviewed_source_v15.py --source-version " + VERSION
    require(original.count(old) == 1, "v14 CI selector differs")
    return original.replace(old, new)


def verify_ci(root=ROOT):
    target = root / ".github/workflows/ci.yml"
    require(not target.is_symlink() and target.is_file()
            and target.read_text() == expected_ci(),
            "CI differs beyond the explicit v15 selector")
    unchanged_file(root, ".github/workflows/p7-engineering.yml",
                   git.blob(BASE, ".github/workflows/p7-engineering.yml"),
                   "P7 engineering workflow changed")


def main():
    if sys.flags.optimize:
        raise SystemExit("source verification requires Python without -O")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-version", required=True, choices=[VERSION])
    parser.parse_args()
    expected = approved_union(load_registry())
    tracked = git.git("ls-files", "--", "crates", "Cargo.toml", "Cargo.lock")
    for path, raw in expected.items():
        unchanged_file(ROOT, path, raw, "v15 complete source input changed")
    git.verify_tree(ROOT, expected, tracked.decode().splitlines())
    validation_tracked = git.git("ls-files", "--", *VALIDATION_ROOTS).decode().splitlines()
    require({path for path in validation_tracked if validation_path(path)}
            == set(validation_inventory(PRODUCT)), "v15 tracked validation inventory differs")
    verify_ci()
    print(json.dumps(dict(identities(), status="passed", complete_inputs=len(expected),
                          executed_previous_proof=previous.VERSION)))


if __name__ == "__main__":
    main()
