import pathlib,json,hashlib,datetime
B=pathlib.Path('/workspace/scratch/a217aaae3bde');O=B/'p8-db-lock-observation-integration';D=O/'future-H-M5-design'
def sha(b):return hashlib.sha256(b).hexdigest()
def oid(b):return hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
def ser(x):return (json.dumps(x,ensure_ascii=False,indent=2,sort_keys=True)+'\n').encode()
prior=json.loads((D/'readonly-composition-design.json').read_bytes());maps=json.loads((D/'expected-product-validation-maps.json').read_bytes());elements=[]
for x in prior['minimal_nonarchive_elements_over_H']:elements.append({k:x[k] for k in ['path','mode','type','sha','sha256','bytes']})
raw=(O/'M6-preparation/new-helper-p8_scale.rs').read_bytes();assert oid(raw)=='02dc35a91dca2be2c8c7d63ff6072c8585c1bef9';path='crates/cc-eval/tests/p8_scale.rs';elements.append({'path':path,'mode':'100644','type':'blob','sha':oid(raw),'sha256':sha(raw),'bytes':len(raw)})
maps['complete_inputs'][path]=sha(raw);maps['delta'][path]['sha256']=sha(raw)
archive=json.loads((O/'M5-review-upload-plan.json').read_bytes())['entries']
for x in archive:elements.append({k:x[k] for k in ['path','mode','type','sha','sha256','bytes']})
new_review='artifacts/checkpoints/p8-canonical-physical-indexes-fixture-preflight-20261009/independent-source-review.json'
elements.append({'path':new_review,'mode':'100644','type':'blob','sha':'933a8e42f9ea87c60f4cd93e116514da1b0f1c5c','bytes':897059,'source':'fixed184 original review object; peer verified original bytes, author will verify actual tree identity'})
parents=['0e6b07c75183da79c5a6679d4c2b66c65f7db663','399386e3111a54cbc8342f0e562b09b199dd5a75','883230f2b44ebcf09495870db8c0e31d61270331','d22d36dddf8b38f1a864c933deefe0b6d3b5baf3']
peers=[]
for n,h in [('H0e6-snapshot-prefix-scoped-review.json','b16d3603618e7538097c3a5495eeb8770208bbadf27c6a174d0825174ba6d6d5'),('PR184-preflight-and-exact-P4-execution-scoped-review.json','2fdeb1460c791ae40d614f8a7cdfc5c0160f71d1120f2de698fb15dc4ff5bf35')]:
 p=B/'PR180-H0e6-review'/n;b=p.read_bytes();assert sha(b)==h;peers.append({'path':str(p),'bytes':len(b),'sha256':h,'git_blob':oid(b)})
assert len(elements)==26 and len(maps['complete_inputs'])==1095 and len(maps['delta'])==71 and len(maps['validation_inputs'])==142
plan={'schema':'M6-fixed-H-M5-helper-main-product-plan-v1','author':'/root/scale_closeout','prepared_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'parents':parents,'base_tree':'9755e717368ffb51bc084c3348c1715b00b34d0d','elements':elements,'element_count':26,'nonarchive_count':4,'archive_addition_count':22,'complete_inputs':maps['complete_inputs'],'delta':maps['delta'],'validation_inputs':maps['validation_inputs'],'product_count':1095,'original_BASE_delta_count':71,'validation_count':142,'complete_inputs_sha256':sha(ser(maps['complete_inputs'])),'validation_inputs_sha256':sha(ser(maps['validation_inputs'])),'peer_reviews':peers,'H_preservation':'Base entire exact H tree, overwrite only the4 declared nonarchive leaves. Preserve all H product inputs, original negative-regression tests, artifacts/docs/tasks/old guards until new exact R/G. The6 H-only DB/test bodies remain exact.','M5_preservation':'Retain its exact21-file checkpoint namespace as additions (official H checkpoint tree proves prefix absent), tie patch and G2 actual push workflow. M5 original source-admission execution remains M5-only.','184_scope':'Select only the fixed883 p8_scale.rs test fixture and its new original review. This fixture adds a new no-descendant --fixture-preflight shell branch; it is not an existing product CLI. Original measured250ms and overall2s unchanged. Earlier fixedP4 one-test Mac success is preserved under its actual identity, not M6.','main_scope':'Take only exact docs/BENCHMARK.md from fixedmain d22; no originaltask field or status edit.','guard_policy':'New exact P/R/registry/review-path with unchanged original v15 algorithm and only4 pin changes; original CLI must await root explicit approval of actual composition.','execution_scope':'No M6 compile, Rust tests, native measurement or source guard executed. No original C or G2 run restart/dispatch.','formal_completion':False,'remaining_todos':29}
b=ser(plan);p=O/'M6-fixed-product-composition-plan.json';p.open('xb').write(b);print(json.dumps({'path':str(p),'bytes':len(b),'sha256':sha(b),'product_manifest':plan['complete_inputs_sha256'],'counts':[1095,71,142],'elements':26}))
