[package]
name = "cc-db"
version.workspace = true
edition.workspace = true

[dependencies]
cc-model = { path = "../cc-model" }
rusqlite.workspace = true
r2d2.workspace = true
r2d2_sqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
regex.workspace = true
blake3.workspace = true
zstd = "0.13"

[dev-dependencies]
tempfile = "3"
